# All sites plot Land Exposure compared to Low Tide

For the selected date range, process Sentinel-2 scenes with less than 10% catalogue cloud cover at all configured sites. For each scene, record the nearest predicted low-tide time, height, and signed time offset; estimate whole-site dry area from SCL vegetation (class 4) and not-vegetated (class 5) pixels. Save per-site CSVs, RGB/SCL galleries, and dry-area-versus-low-tide scatter plots in each site's output folder.

In [1]:
import base64
import datetime
import html as html_module
import io
import os
import sys
import zoneinfo
import pathlib

import dotenv
import geopandas
import matplotlib.pyplot as plt
import numpy
import odc.stac
import pandas
import planetary_computer
import plotly.express as px
import rasterio
import rasterio.features
import requests
import xarray
from IPython.display import FileLink, display

module_path = pathlib.Path.cwd().parent / 'scripts'
import sys
if str(module_path) not in sys.path:
    sys.path.append(str(module_path))
import utils
import sentinel2

In [2]:
data_path = utils.get_data_path()
site_polygons_path = data_path / "site_polygons"
output_root = data_path / "analysis" / "all_sites"
output_root.mkdir(parents=True, exist_ok=True)

dotenv.load_dotenv()
tide_api_key = os.environ.get("TIDE_API")
if not tide_api_key:
    raise ValueError("Set TIDE_API in the environment or project .env file before querying tides.")

## Date-Range Site and Cloud Settings

Set the start and end years and cloud-cover cutoff below. All matching scenes are retained; low-tide timing is recorded for comparison, not used to exclude scenes.

In [7]:
START_YEAR = 2016
END_YEAR = 2025
DATE_RANGE_LABEL = f"{START_YEAR}-{END_YEAR}"
MAX_ITEMS = 400
MAX_CLOUD_COVER_PCT = 10.0
TIDE_SEARCH_RADIUS_HRS = 12

print(f"Years: {DATE_RANGE_LABEL}; STAC item cap per site per year: {MAX_ITEMS}")
print(f"Scene cloud-cover requirement: <{MAX_CLOUD_COVER_PCT:g}%")
print("Dry area: SCL 4 + 5 pixels divided by all rasterized site pixels")

Years: 2016-2025; STAC item cap per site per year: 400
Scene cloud-cover requirement: <10%
Dry area: SCL 4 + 5 pixels divided by all rasterized site pixels

In [8]:
SITES = ("Ihutai", "CatlinsLake", "CatlinsRiverMouth", "Childrens", "Duvauchelle", "Robinsons", "Takamatua", "Purau",
              "IveyBay_Nov25", "IveyBay_Feb26", "LeftBank_Nov25", "LeftBank_Feb26", "Paremata_Nov25", "Paremata_Feb26",
              "Paremata_Feb25", "ThePoint_Nov25", "ThePoint_Feb26", "Takapuwahia_Nov25", "Takapuwahia_Feb26", "IveyBay_ThePoint_LeftBank_Oct24")
SITE_POLYGON_FILES = {
    site_name: site_polygons_path / f"{site_name}_polygon.gpkg"
    for site_name in SITES
}
SITE_OUTPUT_PATHS = {
    site_name: output_root / site_name
    for site_name in SITES
}

for site_name, polygon_file in SITE_POLYGON_FILES.items():
    if not polygon_file.is_file():
        raise FileNotFoundError(f"Missing site polygon for {site_name}: {polygon_file}")
    SITE_OUTPUT_PATHS[site_name].mkdir(parents=True, exist_ok=True)

print(f"Sites: {', '.join(SITES)}")
print(f"Per-site output root: {output_root}")

Sites: Ihutai, CatlinsLake, CatlinsRiverMouth, Childrens, Duvauchelle, Robinsons, Takamatua, Purau, IveyBay_Nov25, IveyBay_Feb26, LeftBank_Nov25, LeftBank_Feb26, Paremata_Nov25, Paremata_Feb26, Paremata_Feb25, ThePoint_Nov25, ThePoint_Feb26, Takapuwahia_Nov25, Takapuwahia_Feb26, IveyBay_ThePoint_LeftBank_Oct24
Per-site output root: C:\Local\repos\seagrass-detection\data\analysis\all_sites

In [21]:
def get_low_tide_info(satellite_datetime_utc, lat, lon):
    """Returns the low tide information for the given satellite image and
      location - low tide height, time and time between the low tide and
      satellite image acquisition.
      lat: Latitude of the location in NZGD49
      lon: Longitude of the location in NZGD49
      """

    dotenv.load_dotenv()
    tide_api_key = os.environ.get("TIDE_API", None)
    if tide_api_key is None:
        raise ValueError("TIDE_API environment variable not set in .env file")

    satellite_time_nz_dt = satellite_datetime_utc.astimezone(
        zoneinfo.ZoneInfo('Pacific/Auckland'))
    start_date = ( # get the date 7hrs before the NZDT satellite time
        satellite_time_nz_dt - datetime.timedelta(hours=7)
        ).strftime(sentinel2.DATE_FORMAT_YYYYMMDD)
    tide_url = ( # Get tide for at least one low tide cyle either side
        f"{sentinel2.TIDE_API_STUB}?lat={lat}&long={lon}&datum=MSL"
        f"&numberOfDays=2&apikey={tide_api_key}&startDate={start_date}"
    )

    tide_query = requests.get(tide_url)
    tide_query.raise_for_status()
    
    tides = pandas.DataFrame.from_records(tide_query.json()["values"])
    tides["time"] = pandas.to_datetime(tides["time"], utc=True)
    tides = tides[tides["value"] < 0] # Low tides only

    time_from_low_tide = (tides["time"] - satellite_datetime_utc).abs().min()
    nearest_low = tides.loc[(tides["time"] - satellite_datetime_utc).abs().idxmin()]

    tide_info = { 
        "nearest_low_tide_height_msl": nearest_low["value"],
        "nearest_low_tide_time_utc": nearest_low["time"],
        "time_from_low_tide": format_tide_duration(time_from_low_tide),
        "hours_from_low_tide": time_from_low_tide.total_seconds() / 3600,
            }

    return tide_info

In [22]:
def format_tide_duration(time_from_low_tide):
    hours_from_low = time_from_low_tide.total_seconds() / 3600
    total_minutes = int(round(abs(float(hours_from_low)) * 60))
    hours, minutes = divmod(total_minutes, 60)
    direction = "at" if total_minutes == 0 else "before" if hours_from_low < 0 else "after"
    return f"{hours}h {minutes:02d}m {direction}"

In [19]:
scl_classes = [
    (0, "No data", "#000000"),
    (1, "Saturated/defective", "#ff0000"),
    (2, "Dark area", "#2f2f2f"),
    (3, "Cloud shadow", "#643200"),
    (4, "Vegetation", "#00a000"),
    (5, "Not vegetated", "#ffe65a"),
    (6, "Water", "#0000ff"),
    (7, "Unclassified", "#808080"),
    (8, "Cloud, medium probability", "#c0c0c0"),
    (9, "Cloud, high probability", "#ffffff"),
    (10, "Thin cirrus", "#64c8ff"),
    (11, "Snow/ice", "#ff96ff"),
]
scl_legend_html = '<div class="legend">' + "".join(
    f'<span class="legend-item"><i style="background:{color}"></i>{code}: '
    f'{html_module.escape(label)}</span>'
    for code, label, color in scl_classes
) + "</div>"


def make_gallery(site_name, gallery_title, cards, output_file, legend_html=""):
    gallery_style = """
:root { color-scheme: light; font-family: "Segoe UI", sans-serif; color: #202a33; background: #f3f5f6; }
body { margin: 0; padding: 20px; }
header, .gallery, .legend { max-width: 1500px; margin: 0 auto 16px; }
h1 { margin: 0 0 6px; font-size: 22px; }
p { margin: 0; color: #56616b; }
.gallery { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(320px, 100%), 1fr)); gap: 14px; }
.scene { min-width: 0; overflow: hidden; background: white; border: 1px solid #d5dce1; border-radius: 5px; }
.scene h2 { margin: 10px 12px 0; font-size: 15px; }
.scene img { display: block; width: 100%; aspect-ratio: 4 / 3; object-fit: contain; background: #f7f8f8; }
.caption { padding: 8px 12px 11px; font-size: 12px; line-height: 1.4; }
.legend { display: flex; flex-wrap: wrap; gap: 6px 12px; padding: 10px; background: white; border: 1px solid #d5dce1; }
.legend-item { display: inline-flex; align-items: center; gap: 5px; font-size: 11px; }
.legend-item i { display: inline-block; width: 14px; height: 14px; border: 1px solid #7b858c; }
@media (max-width: 600px) { body { padding: 10px; } }
"""
    page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html_module.escape(site_name)} {DATE_RANGE_LABEL} {html_module.escape(gallery_title)}</title>
<style>{gallery_style}</style>
</head>
<body>
<header><h1>{html_module.escape(site_name)}: {DATE_RANGE_LABEL} {html_module.escape(gallery_title)}</h1>
<p>{len(cards)} scenes with catalogue cloud cover under {MAX_CLOUD_COVER_PCT:g}%.</p></header>
{legend_html}
<main class="gallery">{''.join(cards)}</main>
</body>
</html>"""
    output_file.write_text(page, encoding="utf-8")
    print(f"  Saved {output_file}")

In [16]:
def harmonize_post_2022(data):
    """Bring post-baseline reflectance bands onto the pre-2022 scale."""

    available_bands = [band for band in sentinel2.BANDS if band in data.data_vars]
    
    post_baseline = data["time"] > numpy.datetime64(sentinel2.HARMONIZE_DATE)
    for band in available_bands:
        if band == "SCL":
            continue
        reflectance = data[band]
        data[band] = xarray.where(
            post_baseline & reflectance.notnull() & (reflectance != 0),
            reflectance.clip(min=sentinel2.BAND_OFFSET_POST_2022_01_25) - sentinel2.BAND_OFFSET_POST_2022_01_25,
            reflectance,
        )
    return data

In [62]:
site_results = {}
for site_name in SITES:
    print(f"\n{site_name}: search {DATE_RANGE_LABEL} Sentinel-2 scenes")
    site_polygon_file = SITE_POLYGON_FILES[site_name]
    site_output_path = SITE_OUTPUT_PATHS[site_name]
    site_polygon = geopandas.read_file(site_polygon_file)
    if site_polygon.crs is None or site_polygon.empty:
        raise ValueError(f"Site polygon must be non-empty and have a CRS: {site_polygon_file}")

    geometry_wgs = site_polygon.buffer(sentinel2.S2_RESOLUTION).to_crs(utils.CRS_WSG)
    stac_items = []
    for year in range(START_YEAR, END_YEAR + 1):
        year_results = sentinel2.stac_search_with_retry(
            url=sentinel2.CATALOGUE_URL,
            max_items=MAX_ITEMS,
            collections=[sentinel2.COLLECTION],
            bbox=geometry_wgs.total_bounds,
            datetime=f"{year}-01-01/{year}-12-31",
            sortby=[{"field": "properties.eo:cloud_cover", "direction": "asc"}],
            get_collection=True,
        )
        stac_items.extend(year_results.items)
        print(f"  {year}: {len(year_results.items)} STAC items")

    cloud_filtered_items = []
    cloud_cover_by_date = {}
    for item in stac_items:
        cloud_cover = item.properties.get("eo:cloud_cover")
        if cloud_cover is None or float(cloud_cover) >= MAX_CLOUD_COVER_PCT:
            continue
        acquisition_time = pandas.to_datetime(item.properties["datetime"], utc=True)
        scene_date = acquisition_time.strftime("%Y-%m-%d")
        cloud_cover = float(cloud_cover)
        cloud_filtered_items.append(item)
        cloud_cover_by_date[scene_date] = min(
            cloud_cover, cloud_cover_by_date.get(scene_date, cloud_cover)
        )

    print(
        f"  STAC items across range: {len(stac_items)}; "
        f"under cloud cutoff: {len(cloud_filtered_items)}"
    )
    if not cloud_filtered_items:
        print(f"  No scenes below {MAX_CLOUD_COVER_PCT:g}% cloud cover")
        continue

    satellite_data = odc.stac.load(
        cloud_filtered_items,
        bbox=geometry_wgs.total_bounds,
        bands=sentinel2.RGB_BANDS + ["SCL", "B11"],
        chunks={},
        groupby="solar_day",
        resolution=sentinel2.S2_RESOLUTION,
        dtype="uint16",
        nodata=0,
        patch_url=planetary_computer.sign,
    )
    satellite_data = satellite_data.rio.clip(
        site_polygon.to_crs(satellite_data.rio.crs).geometry,
        all_touched=True,
        drop=True,
    ).load()
    satellite_data = harmonize_post_2022(satellite_data)
    if satellite_data.sizes.get("time", 0) == 0:
        print("  No cloud-filtered scenes intersect the site polygon")
        continue

    site_polygon_projected = site_polygon.to_crs(satellite_data.rio.crs)
    site_mask_values = rasterio.features.geometry_mask(
        [geometry.__geo_interface__ for geometry in site_polygon_projected.geometry],
        out_shape=(satellite_data.sizes["y"], satellite_data.sizes["x"]),
        transform=satellite_data.rio.transform(),
        invert=True,
        all_touched=True,
    )
    site_mask = xarray.DataArray(
        site_mask_values,
        coords={"y": satellite_data["y"], "x": satellite_data["x"]},
        dims=("y", "x"),
    )
    site_pixel_count = int(site_mask.sum())
    if site_pixel_count == 0:
        raise ValueError(f"No raster pixels fall inside {site_polygon_file}")

    scl_values = satellite_data["SCL"]
    dry_mask = scl_values.isin([4, 5]) & site_mask
    dry_pixel_counts = dry_mask.sum(dim=["x", "y"]).compute().values
    scl_covered_counts = ((scl_values > 0) & site_mask).sum(dim=["x", "y"]).compute().values

    mask = (site_mask & (scl_values > 0) & ~scl_values.isin(sentinel2.SCL_TO_IGNORE))
    valid_scl_percentage = 100 * mask.sum(dim=["x", "y"]) / site_mask.sum()
    

    green = satellite_data["B03"].astype(numpy.float32)
    swir1 = satellite_data["B11"].astype(numpy.float32)
    denominator = green + swir1
    mndwi_valid = (
        site_mask
        & (scl_values > 0)
        & ~scl_values.isin(sentinel2.SCL_TO_IGNORE)
        & (green > 0)
        & (swir1 > 0)
        & (denominator != 0)
    )
    mndwi = ((green - swir1) / denominator).where(mndwi_valid)
    valid_mndwi_count = mndwi.notnull().sum(dim=["x", "y"]).where(
        lambda count: count > 0
    )
    mndwi_stats = xarray.Dataset(
        {
            "mean_mndwi": mndwi.mean(dim=["x", "y"], skipna=True),
            "median_mndwi": mndwi.median(dim=["x", "y"], skipna=True),
            "std_mndwi": mndwi.std(dim=["x", "y"], skipna=True),
            "fraction_mndwi_gt_0": (mndwi > 0).sum(dim=["x", "y"]) / valid_mndwi_count,
            "fraction_mndwi_gt_-0.1": (
                (mndwi > -0.1).sum(dim=["x", "y"]) / valid_mndwi_count
            ),
        }
    ).compute()

    scene_dates = satellite_data.time.dt.strftime("%Y-%m-%d").values.tolist()
    records = []
    centroid_nzgd49 = site_polygon.to_crs(utils.CRS_NZGD49).geometry.union_all().centroid
    latitude_nzgd49 = float(centroid_nzgd49.y)
    longitude_nzgd49 = float(centroid_nzgd49.x)
    for scene_index, scene_date in enumerate(scene_dates):
        satellite_datetime_utc = pandas.Timestamp(
            satellite_data.time.isel(time=scene_index).values
        )
        satellite_datetime_utc = (
            satellite_datetime_utc.tz_localize("UTC")
            if satellite_datetime_utc.tzinfo is None
            else satellite_datetime_utc.tz_convert("UTC")
        )
        tide_info = get_low_tide_info(
            satellite_datetime_utc, latitude_nzgd49, longitude_nzgd49
        )
        records.append(
            {
                "site": site_name,
                "date": scene_date,
                "satellite_time_utc": satellite_datetime_utc,
                "cloud_cover_pct": cloud_cover_by_date.get(scene_date, numpy.nan),
                **tide_info,
                "dry_area_pct": 100 * int(dry_pixel_counts[scene_index]) / site_pixel_count,
                "scl_coverage_pct": (
                    100 * int(scl_covered_counts[scene_index]) / site_pixel_count
                ),
                "valid_scl_pct": float(valid_scl_percentage[scene_index]),
                **{
                    metric: float(mndwi_stats[metric].isel(time=scene_index).values)
                    for metric in mndwi_stats.data_vars
                },
            }
        )

    site_results[site_name] = pandas.DataFrame.from_records(records).reset_index(drop=True)
    site_results[site_name].to_csv(
        site_output_path / f"{site_name}_{DATE_RANGE_LABEL}_low_tide_dry_area.csv",
        index=False,
    )
    print(f"  Saved {len(site_results[site_name])} scene records to {site_output_path}")

    rgb_cards_by_index = {}
    scl_cards_by_index = {}
    for scene_index, row in site_results[site_name].iterrows():
        rgb = numpy.stack(
            [
                satellite_data[band].isel(time=scene_index).values
                for band in sentinel2.RGB_BANDS
            ],
            axis=-1,
        ).astype(numpy.float32)
        rgb_valid = numpy.isfinite(rgb).all(axis=-1) & (rgb > 0).all(axis=-1)
        rgb_display = numpy.ones_like(rgb)
        if rgb_valid.any():
            for channel in range(3):
                pixels = rgb[..., channel][rgb_valid]
                low, high = numpy.percentile(pixels, [2, 98])
                if high > low:
                    rgb_display[..., channel] = numpy.clip(
                        (rgb[..., channel] - low) / (high - low), 0, 1
                    )
        rgb_display[~rgb_valid] = 1
        low_local = pandas.Timestamp(row["nearest_low_tide_time_utc"]).tz_convert(
            "Pacific/Auckland"
        )
        caption = (
            f"Dry {row['dry_area_pct']:.1f}% | MNDWI {row['mean_mndwi']:.3f} | "
            f"Low {low_local:%d %b %H:%M} ({row['time_from_low_tide']}, "
            f"{row['nearest_low_tide_height_msl']:.2f} m MSL) | Valid SCL % {row['valid_scl_pct']}"
        )
        safe_date = html_module.escape(str(row["date"]))

        rgb_buffer = io.BytesIO()
        rgb_figure, rgb_axis = plt.subplots(figsize=(5, 3.75))
        rgb_axis.imshow(rgb_display)
        rgb_axis.axis("off")
        rgb_figure.savefig(
            rgb_buffer,
            format="jpg",
            dpi=90,
            bbox_inches="tight",
            pad_inches=0,
            pil_kwargs={"quality": 84, "optimize": True},
        )
        plt.close(rgb_figure)
        rgb_base64 = base64.b64encode(rgb_buffer.getvalue()).decode("ascii")
        rgb_cards_by_index[scene_index] = (
            f'<article class="scene"><h2>{safe_date}</h2>'
            f'<img src="data:image/jpeg;base64,{rgb_base64}" '
            f'alt="{site_name} RGB {safe_date}">'
            f'<div class="caption">{caption}</div></article>'
        )

        scl_array = satellite_data["SCL"].isel(time=scene_index).values
        scl_rgb = numpy.full((*scl_array.shape, 3), 238, dtype=numpy.uint8)
        for class_code, _, color in scl_classes:
            rgb_color = tuple(int(color[index:index + 2], 16) for index in (1, 3, 5))
            scl_rgb[(scl_array == class_code) & site_mask_values] = rgb_color
        scl_buffer = io.BytesIO()
        scl_figure, scl_axis = plt.subplots(figsize=(5, 3.75))
        scl_axis.imshow(scl_rgb)
        scl_axis.axis("off")
        scl_figure.savefig(
            scl_buffer,
            format="jpg",
            dpi=90,
            bbox_inches="tight",
            pad_inches=0,
            pil_kwargs={"quality": 90, "optimize": True},
        )
        plt.close(scl_figure)
        scl_base64 = base64.b64encode(scl_buffer.getvalue()).decode("ascii")
        scl_cards_by_index[scene_index] = (
            f'<article class="scene"><h2>{safe_date}</h2>'
            f'<img src="data:image/jpeg;base64,{scl_base64}" '
            f'alt="{site_name} SCL {safe_date}">'
            f'<div class="caption">{caption}</div></article>'
        )

    gallery_specs = [
        ("dry_area_pct", "dry_area"),
        ("mean_mndwi", "mean_mndwi"),
        ("median_mndwi", "median_mndwi"),
    ]
    for sort_column, sort_suffix in gallery_specs:
        ordered_indices = site_results[site_name].sort_values(
            sort_column, ascending=False, kind="stable"
        ).index
        make_gallery(
            site_name,
            f"RGB scenes by {sort_column}",
            [rgb_cards_by_index[index] for index in ordered_indices],
            site_output_path / f"{site_name}_{DATE_RANGE_LABEL}_rgb_by_{sort_suffix}.html",
        )
        make_gallery(
            site_name,
            f"SCL scenes by {sort_column}",
            [scl_cards_by_index[index] for index in ordered_indices],
            site_output_path / f"{site_name}_{DATE_RANGE_LABEL}_scl_by_{sort_suffix}.html",
            scl_legend_html,
        )

    scatter_data = site_results[site_name].copy()
    acquisition_times = pandas.to_datetime(scatter_data["satellite_time_utc"], utc=True)
    scatter_data["date_color"] = acquisition_times.astype("int64") / 1e9
    year_midpoints = acquisition_times.groupby(acquisition_times.dt.year).median()
    color_ticks = (year_midpoints.astype("int64") / 1e9).tolist()
    color_tick_labels = year_midpoints.index.astype(str).tolist()
    scatter_data["abs_hours_from_low_tide"] = scatter_data["hours_from_low_tide"].abs()
    scatter = px.scatter(
        scatter_data,
        x="abs_hours_from_low_tide",
        y="dry_area_pct",
        color="date_color",
        color_continuous_scale="Viridis",
        hover_name="date",
        hover_data={
            "time_from_low_tide": True,
            "nearest_low_tide_height_msl": ":.2f",
            "cloud_cover_pct": ":.1f",
            "valid_scl_pct": ":.1f",
            "scl_coverage_pct": ":.1f",
            "mean_mndwi": ":.3f",
            "date_color": False,
        },
        labels={
            "abs_hours_from_low_tide": "Absolute duration from low tide (hours)",
            "dry_area_pct": "Dry area (SCL 4+5, % of site)",
            "date_color": "Acquisition year",
        },
        title=f"{site_name}: Dry area vs time from low tide ({DATE_RANGE_LABEL})",
    )
    scatter.update_layout(
        height=650,
        hovermode="closest",
        coloraxis_colorbar={
            "title": "Acquisition year",
            "tickvals": color_ticks,
            "ticktext": color_tick_labels,
        },
        yaxis={"range": [0, 100]},
    )
    scatter_file = site_output_path / f"{site_name}_{DATE_RANGE_LABEL}_dry_vs_low_tide.html"
    scatter.write_html(scatter_file, include_plotlyjs=True, auto_open=False)


    scatter = px.scatter(
        scatter_data,
        x="abs_hours_from_low_tide",
        y="mean_mndwi",
        color="date_color",
        color_continuous_scale="Viridis",
        hover_name="date",
        hover_data={
            "time_from_low_tide": True,
            "nearest_low_tide_height_msl": ":.2f",
            "cloud_cover_pct": ":.1f",
            "valid_scl_pct": ":.1f",
            "scl_coverage_pct": ":.1f",
            "mean_mndwi": ":.3f",
            "date_color": False,
        },
        labels={
            "abs_hours_from_low_tide": "Absolute duration from low tide (hours)",
            "dry_area_pct": "Dry area (SCL 4+5, % of site)",
            "date_color": "Acquisition year",
        },
        title=f"{site_name}: Dry area vs time from low tide ({DATE_RANGE_LABEL})",
    )
    scatter.update_layout(
        height=650,
        hovermode="closest",
        coloraxis_colorbar={
            "title": "Acquisition year",
            "tickvals": color_ticks,
            "ticktext": color_tick_labels,
        },
        yaxis={"range": [-.2, 1.2]},
    )
    scatter_file = site_output_path / f"{site_name}_{DATE_RANGE_LABEL}_mean_mndwi_vs_low_tide.html"
    scatter.write_html(scatter_file, include_plotlyjs=True, auto_open=False)

    # plot mean mndwi after clody images removed
    scatter_data = site_results[site_name].copy()
    scatter_data = scatter_data[scatter_data['valid_scl_pct'] > 99]
    acquisition_times = pandas.to_datetime(scatter_data["satellite_time_utc"], utc=True)
    scatter_data["date_color"] = acquisition_times.astype("int64") / 1e9
    year_midpoints = acquisition_times.groupby(acquisition_times.dt.year).median()
    color_ticks = (year_midpoints.astype("int64") / 1e9).tolist()
    color_tick_labels = year_midpoints.index.astype(str).tolist()
    scatter_data["abs_hours_from_low_tide"] = scatter_data["hours_from_low_tide"].abs()

    scatter = px.scatter(
        scatter_data,
        x="abs_hours_from_low_tide",
        y="mean_mndwi",
        color="date_color",
        color_continuous_scale="Viridis",
        hover_name="date",
        hover_data={
            "time_from_low_tide": True,
            "nearest_low_tide_height_msl": ":.2f",
            "cloud_cover_pct": ":.1f",
            "valid_scl_pct": ":.1f",
            "scl_coverage_pct": ":.1f",
            "mean_mndwi": ":.3f",
            "date_color": False,
        },
        labels={
            "abs_hours_from_low_tide": "Absolute duration from low tide (hours)",
            "dry_area_pct": "Dry area (SCL 4+5, % of site)",
            "date_color": "Acquisition year",
        },
        title=f"{site_name}: Dry area vs time from low tide ({DATE_RANGE_LABEL})",
    )
    scatter.update_layout(
        height=650,
        hovermode="closest",
        coloraxis_colorbar={
            "title": "Acquisition year",
            "tickvals": color_ticks,
            "ticktext": color_tick_labels,
        },
        yaxis={"range": [-.2, 1.2]},
    )
    scatter_file = site_output_path / f"{site_name}_{DATE_RANGE_LABEL}_low_cloud_mean_mndwi_vs_low_tide.html"
    scatter.write_html(scatter_file, include_plotlyjs=True, auto_open=False)
    

    print(f"  Saved scatter: {scatter_file}")
    display(site_results[site_name])
    for sort_suffix in ("dry_area", "mean_mndwi"):
        display(
            FileLink(
                str(site_output_path / f"{site_name}_{DATE_RANGE_LABEL}_rgb_by_{sort_suffix}.html")
            )
        )
        display(
            FileLink(
                str(site_output_path / f"{site_name}_{DATE_RANGE_LABEL}_scl_by_{sort_suffix}.html")
            )
        )
    display(FileLink(str(scatter_file)))

Ihutai: search 2016-2025 Sentinel-2 scenes
  2016: 53 STAC items
  2017: 44 STAC items
  2018: 73 STAC items
  2019: 68 STAC items
  2020: 72 STAC items
  2021: 74 STAC items
  2022: 115 STAC items
  2023: 129 STAC items
  2024: 74 STAC items
  2025: 70 STAC items
  STAC items across range: 772; under cloud cutoff: 110
  Saved 97 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Ihutai,2016-02-09,2016-02-09 22:25:32.030000+00:00,1.493319,-1.11,2016-02-09 23:48:00+00:00,1h 22m after,1.374436,6.976334,99.990604,99.682894,0.407335,0.642369,0.410964,0.776483,0.831800
1,Ihutai,2016-02-19,2016-02-19 22:25:32.029000+00:00,2.657386,-0.88,2016-02-19 20:41:00+00:00,1h 45m after,1.742230,8.410359,99.971813,99.255388,0.242533,0.140777,0.454539,0.641680,0.751594
2,Ihutai,2016-04-09,2016-04-09 22:25:32.030000+00:00,9.514942,-1.23,2016-04-10 00:47:00+00:00,2h 21m after,2.357769,7.820776,100.000000,68.379823,0.430036,0.527711,0.443890,0.792261,0.864158
3,Ihutai,2016-04-26,2016-04-26 22:15:52.028000+00:00,0.008174,-0.71,2016-04-27 02:09:00+00:00,3h 53m after,3.885548,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
4,Ihutai,2016-05-06,2016-05-06 22:15:52.027000+00:00,0.110175,-1.25,2016-05-06 22:34:00+00:00,0h 18m after,0.302215,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Ihutai,2025-09-14,2025-09-14 22:25:39.024000+00:00,7.040510,-0.94,2025-09-14 16:19:00+00:00,6h 07m after,6.110840,12.769981,100.000000,100.000000,0.710656,0.937239,0.450412,0.867469,0.884857
93,Ihutai,2025-09-29,2025-09-29 22:26:01.025000+00:00,6.435211,-0.60,2025-09-29 16:08:00+00:00,6h 18m after,6.300285,14.317928,100.000000,100.000000,0.651604,0.878646,0.453175,0.851389,0.868091
94,Ihutai,2025-10-24,2025-10-24 22:25:39.024000+00:00,0.326880,-0.67,2025-10-25 01:14:00+00:00,2h 48m after,2.805827,12.543308,100.000000,100.000000,0.685268,0.920768,0.449063,0.862403,0.887056
95,Ihutai,2025-10-29,2025-10-29 22:26:01.025000+00:00,2.153105,-0.61,2025-10-29 16:15:00+00:00,6h 11m after,6.183618,14.255681,100.000000,100.000000,0.643408,0.863226,0.446076,0.845945,0.862998
96,Ihutai,2025-12-23,2025-12-23 22:25:39.024000+00:00,0.585297,-0.75,2025-12-24 01:45:00+00:00,3h 19m after,3.322493,12.862764,100.000000,100.000000,0.555914,0.706199,0.393214,0.858289,0.882060

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Ihutai\Ihutai_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

CatlinsLake: search 2016-2025 Sentinel-2 scenes
  2016: 63 STAC items
  2017: 104 STAC items
  2018: 146 STAC items
  2019: 139 STAC items
  2020: 143 STAC items
  2021: 150 STAC items
  2022: 185 STAC items
  2023: 246 STAC items
  2024: 140 STAC items
  2025: 131 STAC items
  STAC items across range: 1447; under cloud cutoff: 128
  Saved 105 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,CatlinsLake,2016-01-10,2016-01-10 22:25:42.030000+00:00,0.277551,-0.93,2016-01-10 21:29:00+00:00,0h 57m after,0.945008,3.694931,100.000000,100.000000,0.436561,0.570934,0.382188,0.846090,0.917078
1,CatlinsLake,2016-02-02,2016-02-02 22:35:22.030000+00:00,0.397603,-0.60,2016-02-03 04:38:00+00:00,6h 03m after,6.043881,2.871580,99.936839,99.927816,0.715017,0.818182,0.312652,0.936251,0.946500
2,CatlinsLake,2016-05-02,2016-05-02 22:35:42.027000+00:00,0.068493,-0.92,2016-05-02 17:14:00+00:00,5h 22m after,5.361674,2.330198,100.000000,99.352598,0.616707,0.743529,0.386682,0.916833,0.924780
3,CatlinsLake,2016-07-21,2016-07-21 22:37:12.026000+00:00,4.201390,-0.92,2016-07-21 22:06:00+00:00,0h 31m after,0.520007,2.170039,100.000000,97.597618,0.523717,0.732503,0.434357,0.858110,0.901262
4,CatlinsLake,2016-08-10,2016-08-10 22:37:12.026000+00:00,1.886789,-0.54,2016-08-11 03:15:00+00:00,4h 38m after,4.629993,1.786560,100.000000,94.904243,0.792636,0.961538,0.411885,0.932687,0.936110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,CatlinsLake,2025-04-10,2025-04-10 22:37:09.024000+00:00,4.059831,-0.83,2025-04-10 19:39:00+00:00,2h 58m after,2.969173,10.173468,100.000000,100.000000,0.208648,0.073858,0.426549,0.596782,0.763654
101,CatlinsLake,2025-06-16,2025-06-16 22:25:39.024000+00:00,5.443942,-0.71,2025-06-17 00:59:00+00:00,2h 33m after,2.555827,4.825066,100.000000,99.214996,0.692161,0.879070,0.398778,0.889349,0.909221
102,CatlinsLake,2025-09-07,2025-09-07 22:37:09.024000+00:00,2.634845,-1.01,2025-09-07 20:34:00+00:00,2h 03m after,2.052507,9.925334,100.000000,100.000000,0.287205,0.170124,0.417046,0.718250,0.850658
103,CatlinsLake,2025-10-09,2025-10-09 22:26:01.025000+00:00,0.998645,-1.02,2025-10-09 22:47:00+00:00,0h 21m after,0.349715,9.244096,100.000000,98.157046,0.518620,0.616715,0.273818,0.930298,0.943742
104,CatlinsLake,2025-10-22,2025-10-22 22:37:21.025000+00:00,6.125554,-0.74,2025-10-22 21:37:00+00:00,1h 00m after,1.005840,4.019760,100.000000,99.819539,0.479822,0.596010,0.301822,0.906906,0.936770

C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsLake\CatlinsLake_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

CatlinsRiverMouth: search 2016-2025 Sentinel-2 scenes
  2016: 124 STAC items
  2017: 212 STAC items
  2018: 291 STAC items
  2019: 278 STAC items
  2020: 283 STAC items
  2021: 304 STAC items
  2022: 385 STAC items
  2023: 400 STAC items
  2024: 275 STAC items
  2025: 263 STAC items
  STAC items across range: 2815; under cloud cutoff: 249
  Saved 149 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,CatlinsRiverMouth,2016-01-10,2016-01-10 22:25:42.030000+00:00,0.277551,-0.92,2016-01-10 21:31:00+00:00,0h 55m after,0.911675,23.048624,100.0,99.776072,-0.006122,0.017341,0.315126,0.543764,0.696698
1,CatlinsRiverMouth,2016-02-02,2016-02-02 22:35:22.030000+00:00,0.028494,-0.60,2016-02-03 04:40:00+00:00,6h 05m after,6.077214,22.936660,100.0,99.616123,0.514150,0.849814,0.579335,0.743256,0.756904
2,CatlinsRiverMouth,2016-04-09,2016-04-09 22:25:32.030000+00:00,6.750651,-1.14,2016-04-09 22:52:00+00:00,0h 26m after,0.441103,25.719770,100.0,98.656430,0.006237,0.026872,0.403833,0.534047,0.639591
3,CatlinsRiverMouth,2016-05-02,2016-05-02 22:35:42.027000+00:00,0.012499,-0.91,2016-05-02 17:16:00+00:00,5h 20m after,5.328341,19.929623,100.0,98.656430,0.515479,0.826628,0.578984,0.767510,0.780156
4,CatlinsRiverMouth,2016-07-21,2016-07-21 22:37:12.026000+00:00,4.201390,-0.91,2016-07-21 22:09:00+00:00,0h 28m after,0.470007,19.049904,100.0,98.016635,0.008437,0.005142,0.378860,0.507343,0.641319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,CatlinsRiverMouth,2025-07-19,2025-07-19 22:37:09.024000+00:00,0.218554,-0.77,2025-07-20 04:44:00+00:00,6h 07m after,6.114160,22.376839,100.0,99.504159,0.467416,0.873278,0.620577,0.692024,0.709453
145,CatlinsRiverMouth,2025-08-25,2025-08-25 22:25:49.024000+00:00,6.799818,-0.83,2025-08-25 22:35:00+00:00,0h 09m after,0.153049,29.734485,100.0,100.000000,0.051065,0.059647,0.377752,0.574376,0.686020
146,CatlinsRiverMouth,2025-09-07,2025-09-07 22:37:09.024000+00:00,2.634845,-1.00,2025-09-07 20:36:00+00:00,2h 01m after,2.019173,29.830454,100.0,100.000000,0.040647,0.015308,0.397704,0.524504,0.670564
147,CatlinsRiverMouth,2025-10-09,2025-10-09 22:26:01.025000+00:00,0.998645,-1.01,2025-10-09 22:50:00+00:00,0h 24m after,0.399715,29.126679,100.0,91.282790,0.113770,0.093827,0.438106,0.591204,0.687752
148,CatlinsRiverMouth,2025-10-22,2025-10-22 22:37:21.025000+00:00,6.125554,-0.73,2025-10-22 21:39:00+00:00,0h 58m after,0.972507,26.167626,100.0,100.000000,0.244628,0.241045,0.478071,0.662828,0.738644

C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\CatlinsRiverMouth\CatlinsRiverMouth_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

Childrens: search 2016-2025 Sentinel-2 scenes
  2016: 67 STAC items
  2017: 90 STAC items
  2018: 141 STAC items
  2019: 134 STAC items
  2020: 144 STAC items
  2021: 152 STAC items
  2022: 183 STAC items
  2023: 242 STAC items
  2024: 145 STAC items
  2025: 140 STAC items
  STAC items across range: 1438; under cloud cutoff: 223
  Saved 199 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Childrens,2016-02-09,2016-02-09 22:25:32.030000+00:00,1.493319,-1.12,2016-02-09 23:03:00+00:00,0h 37m after,0.624436,6.809891,100.0,100.000000,0.295675,0.269841,0.440275,0.683016,0.778679
1,Childrens,2016-02-19,2016-02-19 22:25:32.029000+00:00,2.657386,-0.91,2016-02-19 20:03:00+00:00,2h 23m after,2.375564,6.080259,100.0,100.000000,0.522593,0.796502,0.464764,0.795298,0.830563
2,Childrens,2016-04-09,2016-04-09 22:25:32.030000+00:00,9.514942,-1.19,2016-04-10 00:03:00+00:00,1h 37m after,1.624436,3.121200,100.0,87.150385,0.300060,0.263724,0.336187,0.760465,0.889302
3,Childrens,2016-04-26,2016-04-26 22:15:52.028000+00:00,0.008174,-0.65,2016-04-27 01:25:00+00:00,3h 09m after,3.152214,3.567086,100.0,100.000000,0.581384,0.810101,0.448696,0.841508,0.862991
4,Childrens,2016-05-06,2016-05-06 22:15:52.027000+00:00,0.110175,-1.23,2016-05-06 21:51:00+00:00,0h 25m after,0.414452,3.648156,100.0,99.837860,0.321301,0.307359,0.522273,0.691027,0.764921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,Childrens,2025-10-24,2025-10-24 22:25:39.024000+00:00,0.326880,-0.67,2025-10-25 00:27:00+00:00,2h 01m after,2.022493,8.674503,100.0,100.000000,0.520545,0.775076,0.477959,0.785570,0.821240
195,Childrens,2025-10-29,2025-10-29 22:26:01.025000+00:00,2.153105,-0.66,2025-10-30 04:27:00+00:00,6h 01m after,6.016382,8.958249,100.0,100.000000,0.573128,0.766443,0.419908,0.839887,0.866640
196,Childrens,2025-11-10,2025-11-10 22:15:59.024000+00:00,9.393936,-0.96,2025-11-11 02:51:00+00:00,4h 35m after,4.583604,2.837454,100.0,57.478719,0.574620,0.699163,0.290992,0.914669,0.943583
197,Childrens,2025-11-15,2025-11-15 22:16:11.025000+00:00,4.976140,-0.72,2025-11-15 18:45:00+00:00,3h 31m after,3.519729,7.904337,100.0,76.489664,0.512194,0.724138,0.430348,0.808691,0.833598
198,Childrens,2025-12-23,2025-12-23 22:25:39.024000+00:00,0.585297,-0.75,2025-12-24 00:58:00+00:00,2h 32m after,2.539160,8.633968,100.0,100.000000,0.515833,0.753036,0.438505,0.803405,0.835428

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Childrens\Childrens_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

Duvauchelle: search 2016-2025 Sentinel-2 scenes
  2016: 67 STAC items
  2017: 90 STAC items
  2018: 141 STAC items
  2019: 134 STAC items
  2020: 144 STAC items
  2021: 152 STAC items
  2022: 183 STAC items
  2023: 242 STAC items
  2024: 145 STAC items
  2025: 140 STAC items
  STAC items across range: 1438; under cloud cutoff: 223
  Saved 199 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Duvauchelle,2016-02-09,2016-02-09 22:25:32.030000+00:00,1.493319,-1.13,2016-02-09 23:03:00+00:00,0h 37m after,0.624436,3.471097,100.000000,100.000000,0.303318,0.242640,0.413256,0.625068,0.819692
1,Duvauchelle,2016-02-19,2016-02-19 22:25:32.029000+00:00,2.657386,-0.91,2016-02-19 20:03:00+00:00,2h 23m after,2.375564,3.052404,99.702863,99.702863,0.529464,0.828795,0.485525,0.747223,0.847873
2,Duvauchelle,2016-04-09,2016-04-09 22:25:32.030000+00:00,9.514942,-1.20,2016-04-10 00:03:00+00:00,1h 37m after,1.624436,2.512156,100.000000,20.097245,0.063825,0.064840,0.103063,0.744624,0.950941
3,Duvauchelle,2016-04-26,2016-04-26 22:15:52.028000+00:00,0.008174,-0.65,2016-04-27 01:24:00+00:00,3h 08m after,3.135548,3.268504,100.000000,100.000000,0.635414,0.874116,0.442309,0.864127,0.890059
4,Duvauchelle,2016-05-06,2016-05-06 22:15:52.027000+00:00,0.110175,-1.24,2016-05-06 21:51:00+00:00,0h 25m after,0.414452,3.552134,100.000000,100.000000,0.348480,0.212088,0.517955,0.619125,0.765667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,Duvauchelle,2025-10-24,2025-10-24 22:25:39.024000+00:00,0.326880,-0.67,2025-10-25 00:26:00+00:00,2h 00m after,2.005827,7.590492,100.000000,100.000000,0.500842,0.767106,0.454443,0.757023,0.870475
195,Duvauchelle,2025-10-29,2025-10-29 22:26:01.025000+00:00,2.153105,-0.67,2025-10-30 04:27:00+00:00,6h 01m after,6.016382,7.225824,100.000000,100.000000,0.622573,0.764045,0.348938,0.896677,0.912345
196,Duvauchelle,2025-11-10,2025-11-10 22:15:59.024000+00:00,9.393936,-0.96,2025-11-11 02:51:00+00:00,4h 35m after,4.583604,3.363047,100.000000,82.252836,0.606600,0.757636,0.293561,0.932841,0.961905
197,Duvauchelle,2025-11-15,2025-11-15 22:16:11.025000+00:00,4.976140,-0.73,2025-11-15 18:45:00+00:00,3h 31m after,3.519729,7.671529,100.000000,100.000000,0.511000,0.736583,0.414626,0.782955,0.827391
198,Duvauchelle,2025-12-23,2025-12-23 22:25:39.024000+00:00,0.585297,-0.75,2025-12-24 00:58:00+00:00,2h 32m after,2.539160,2.498649,100.000000,68.584549,0.364298,0.476824,0.310567,0.823356,0.890311

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Duvauchelle\Duvauchelle_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

Robinsons: search 2016-2025 Sentinel-2 scenes
  2016: 67 STAC items
  2017: 90 STAC items
  2018: 141 STAC items
  2019: 134 STAC items
  2020: 144 STAC items
  2021: 152 STAC items
  2022: 183 STAC items
  2023: 242 STAC items
  2024: 145 STAC items
  2025: 140 STAC items
  STAC items across range: 1438; under cloud cutoff: 223
  Saved 199 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Robinsons,2016-02-09,2016-02-09 22:25:32.030000+00:00,1.493319,-1.13,2016-02-09 23:03:00+00:00,0h 37m after,0.624436,4.012494,100.0,100.000000,0.259673,0.130811,0.410298,0.644642,0.807544
1,Robinsons,2016-02-19,2016-02-19 22:25:32.029000+00:00,2.657386,-0.91,2016-02-19 20:03:00+00:00,2h 23m after,2.375564,3.628063,100.0,100.000000,0.506547,0.786054,0.454944,0.764056,0.834455
2,Robinsons,2016-04-09,2016-04-09 22:25:32.030000+00:00,9.514942,-1.20,2016-04-10 00:03:00+00:00,1h 37m after,1.624436,0.480538,100.0,81.619414,0.275715,0.255919,0.264776,0.812187,0.932293
3,Robinsons,2016-04-26,2016-04-26 22:15:52.028000+00:00,0.008174,-0.65,2016-04-27 01:25:00+00:00,3h 09m after,3.152214,2.306583,100.0,100.000000,0.629399,0.820216,0.415317,0.873378,0.902931
4,Robinsons,2016-05-06,2016-05-06 22:15:52.027000+00:00,0.110175,-1.24,2016-05-06 21:51:00+00:00,0h 25m after,0.414452,2.090341,100.0,99.807785,0.238835,0.052850,0.476085,0.603515,0.780693
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,Robinsons,2025-10-24,2025-10-24 22:25:39.024000+00:00,0.326880,-0.67,2025-10-25 00:27:00+00:00,2h 01m after,2.022493,6.943777,100.0,100.000000,0.579057,0.849673,0.445278,0.817155,0.878904
195,Robinsons,2025-10-29,2025-10-29 22:26:01.025000+00:00,2.153105,-0.67,2025-10-30 04:27:00+00:00,6h 01m after,6.016382,6.174916,100.0,100.000000,0.665484,0.813526,0.351109,0.905094,0.919029
196,Robinsons,2025-11-10,2025-11-10 22:15:59.024000+00:00,9.393936,-0.96,2025-11-11 02:51:00+00:00,4h 35m after,4.583604,2.907256,100.0,68.428640,0.695021,0.787523,0.249845,0.950843,0.963132
197,Robinsons,2025-11-15,2025-11-15 22:16:11.025000+00:00,4.976140,-0.73,2025-11-15 18:45:00+00:00,3h 31m after,3.519729,9.730899,100.0,71.768381,0.233215,0.130808,0.353253,0.628390,0.822230
198,Robinsons,2025-12-23,2025-12-23 22:25:39.024000+00:00,0.585297,-0.75,2025-12-24 00:58:00+00:00,2h 32m after,2.539160,6.607400,100.0,100.000000,0.547863,0.743734,0.408805,0.834455,0.884671

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Robinsons\Robinsons_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

Takamatua: search 2016-2025 Sentinel-2 scenes
  2016: 67 STAC items
  2017: 90 STAC items
  2018: 141 STAC items
  2019: 134 STAC items
  2020: 144 STAC items
  2021: 152 STAC items
  2022: 183 STAC items
  2023: 242 STAC items
  2024: 145 STAC items
  2025: 140 STAC items
  STAC items across range: 1438; under cloud cutoff: 223
  Saved 199 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Takamatua,2016-02-09,2016-02-09 22:25:32.030000+00:00,1.493319,-1.13,2016-02-09 23:03:00+00:00,0h 37m after,0.624436,4.049750,100.0,100.000000,0.316718,0.281369,0.413898,0.703018,0.828606
1,Takamatua,2016-02-19,2016-02-19 22:25:32.029000+00:00,2.657386,-0.91,2016-02-19 20:03:00+00:00,2h 23m after,2.375564,2.153799,100.0,80.433793,0.681197,0.832335,0.358202,0.915331,0.930794
2,Takamatua,2016-04-09,2016-04-09 22:25:32.030000+00:00,9.514942,-1.20,2016-04-10 00:03:00+00:00,1h 37m after,1.624436,0.940391,100.0,58.258759,0.229652,0.172343,0.284913,0.721166,0.901067
3,Takamatua,2016-04-26,2016-04-26 22:15:52.028000+00:00,0.008174,-0.65,2016-04-27 01:25:00+00:00,3h 09m after,3.152214,3.094191,100.0,100.000000,0.658712,0.839034,0.403515,0.875322,0.895040
4,Takamatua,2016-05-06,2016-05-06 22:15:52.027000+00:00,0.110175,-1.24,2016-05-06 21:52:00+00:00,0h 24m after,0.397785,2.988018,100.0,100.000000,0.318555,0.184369,0.483500,0.716366,0.824663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,Takamatua,2025-10-24,2025-10-24 22:25:39.024000+00:00,0.326880,-0.67,2025-10-25 00:27:00+00:00,2h 01m after,2.022493,5.566510,100.0,100.000000,0.694684,0.922830,0.434867,0.870146,0.900334
195,Takamatua,2025-10-29,2025-10-29 22:26:01.025000+00:00,2.153105,-0.67,2025-10-30 04:27:00+00:00,6h 01m after,6.016382,5.399666,100.0,100.000000,0.696549,0.802406,0.326215,0.919296,0.931432
196,Takamatua,2025-11-10,2025-11-10 22:15:59.024000+00:00,9.393936,-0.96,2025-11-11 02:51:00+00:00,4h 35m after,4.583604,1.440922,100.0,78.431670,0.734422,0.783871,0.207999,0.967705,0.975827
197,Takamatua,2025-11-15,2025-11-15 22:16:11.025000+00:00,4.976140,-0.73,2025-11-15 18:45:00+00:00,3h 31m after,3.519729,6.658577,100.0,98.468072,0.670733,0.823391,0.361531,0.895872,0.914356
198,Takamatua,2025-12-23,2025-12-23 22:25:39.024000+00:00,0.585297,-0.75,2025-12-24 00:58:00+00:00,2h 32m after,2.539160,6.886091,100.0,100.000000,0.686366,0.880208,0.405834,0.871834,0.905658

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takamatua\Takamatua_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

Purau: search 2016-2025 Sentinel-2 scenes
  2016: 53 STAC items
  2017: 44 STAC items
  2018: 73 STAC items
  2019: 68 STAC items
  2020: 72 STAC items
  2021: 74 STAC items
  2022: 115 STAC items
  2023: 129 STAC items
  2024: 73 STAC items
  2025: 70 STAC items
  STAC items across range: 771; under cloud cutoff: 110
  Saved 97 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Purau,2016-02-09,2016-02-09 22:25:32.030000+00:00,1.493319,-1.13,2016-02-09 23:47:00+00:00,1h 21m after,1.357769,5.460655,100.0,98.655839,0.390430,0.635060,0.442646,0.735453,0.806415
1,Purau,2016-02-19,2016-02-19 22:25:32.029000+00:00,2.657386,-0.90,2016-02-19 20:40:00+00:00,1h 46m after,1.758897,4.928591,100.0,98.431812,0.548791,0.856016,0.493785,0.782930,0.820199
2,Purau,2016-04-09,2016-04-09 22:25:32.030000+00:00,9.514942,-1.26,2016-04-10 00:46:00+00:00,2h 20m after,2.341103,3.388407,100.0,65.163820,0.144458,0.070930,0.301134,0.633863,0.802750
3,Purau,2016-04-26,2016-04-26 22:15:52.028000+00:00,0.008174,-0.72,2016-04-27 02:08:00+00:00,3h 52m after,3.868881,0.000000,0.0,0.000000,NaN,NaN,NaN,NaN,NaN
4,Purau,2016-05-06,2016-05-06 22:15:52.027000+00:00,0.110175,-1.28,2016-05-06 22:33:00+00:00,0h 17m after,0.285548,0.000000,0.0,0.000000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Purau,2025-09-14,2025-09-14 22:25:39.024000+00:00,7.040510,-0.96,2025-09-14 16:18:00+00:00,6h 08m after,6.127507,18.510221,100.0,100.000000,0.614916,0.843587,0.445673,0.837581,0.859983
93,Purau,2025-09-29,2025-09-29 22:26:01.025000+00:00,6.435211,-0.62,2025-09-29 16:07:00+00:00,6h 19m after,6.316951,19.434332,100.0,100.000000,0.609302,0.831063,0.430380,0.841221,0.863624
94,Purau,2025-10-24,2025-10-24 22:25:39.024000+00:00,0.326880,-0.69,2025-10-25 01:12:00+00:00,2h 46m after,2.772493,15.933912,100.0,100.000000,0.589051,0.834933,0.448756,0.823299,0.852422
95,Purau,2025-10-29,2025-10-29 22:26:01.025000+00:00,2.153105,-0.63,2025-10-29 16:15:00+00:00,6h 11m after,6.183618,14.813778,100.0,100.000000,0.607148,0.819369,0.413629,0.848782,0.870905
96,Purau,2025-12-23,2025-12-23 22:25:39.024000+00:00,0.585297,-0.77,2025-12-24 01:44:00+00:00,3h 18m after,3.305827,13.497620,100.0,100.000000,0.539535,0.765144,0.431027,0.810137,0.842901

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Purau\Purau_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

IveyBay_Nov25: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 91 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1433; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,IveyBay_Nov25,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.41,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,5.899705,100.0,99.410029,0.293160,0.303201,0.416401,0.658754,0.738872
1,IveyBay_Nov25,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:42:00+00:00,4h 16m after,4.274436,7.669617,100.0,97.050147,0.325041,0.464286,0.332487,0.781155,0.851064
2,IveyBay_Nov25,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.41,2016-03-21 03:03:00+00:00,4h 37m after,4.624436,1.769912,100.0,100.000000,0.402800,0.553957,0.342593,0.825959,0.873156
3,IveyBay_Nov25,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.52,2016-04-26 18:10:00+00:00,4h 06m after,4.097786,8.259587,100.0,100.000000,0.221589,0.334096,0.386088,0.643068,0.705015
4,IveyBay_Nov25,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,2.949853,100.0,100.000000,0.218005,0.258741,0.371963,0.648968,0.696165
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,IveyBay_Nov25,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:11:00+00:00,5h 15m after,5.250285,24.483776,100.0,100.000000,0.314945,0.491208,0.331398,0.769912,0.834808
180,IveyBay_Nov25,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,23.893805,100.0,100.000000,0.340422,0.493923,0.422740,0.719764,0.769912
181,IveyBay_Nov25,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.17,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,22.713864,100.0,100.000000,0.217174,0.350711,0.333079,0.702065,0.764012
182,IveyBay_Nov25,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:19:00+00:00,4h 07m after,4.114174,20.648968,100.0,100.000000,0.193880,0.300113,0.304196,0.705015,0.778761
183,IveyBay_Nov25,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.47,2025-12-23 18:02:00+00:00,4h 24m after,4.394173,23.598820,100.0,96.460177,0.178661,0.170515,0.207157,0.782875,0.899083

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Nov25\IveyBay_Nov25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

IveyBay_Feb26: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 91 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1433; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,IveyBay_Feb26,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.41,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,5.899705,100.0,99.410029,0.293160,0.303201,0.416401,0.658754,0.738872
1,IveyBay_Feb26,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:42:00+00:00,4h 16m after,4.274436,7.669617,100.0,97.050147,0.325041,0.464286,0.332487,0.781155,0.851064
2,IveyBay_Feb26,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.41,2016-03-21 03:03:00+00:00,4h 37m after,4.624436,1.769912,100.0,100.000000,0.402800,0.553957,0.342593,0.825959,0.873156
3,IveyBay_Feb26,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.52,2016-04-26 18:10:00+00:00,4h 06m after,4.097786,8.259587,100.0,100.000000,0.221589,0.334096,0.386088,0.643068,0.705015
4,IveyBay_Feb26,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,2.949853,100.0,100.000000,0.218005,0.258741,0.371963,0.648968,0.696165
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,IveyBay_Feb26,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:11:00+00:00,5h 15m after,5.250285,24.483776,100.0,100.000000,0.314945,0.491208,0.331398,0.769912,0.834808
180,IveyBay_Feb26,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,23.893805,100.0,100.000000,0.340422,0.493923,0.422740,0.719764,0.769912
181,IveyBay_Feb26,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.17,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,22.713864,100.0,100.000000,0.217174,0.350711,0.333079,0.702065,0.764012
182,IveyBay_Feb26,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:19:00+00:00,4h 07m after,4.114174,20.648968,100.0,100.000000,0.193880,0.300113,0.304196,0.705015,0.778761
183,IveyBay_Feb26,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.47,2025-12-23 18:02:00+00:00,4h 24m after,4.394173,23.598820,100.0,96.460177,0.178661,0.170515,0.207157,0.782875,0.899083

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_Feb26\IveyBay_Feb26_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

LeftBank_Nov25: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 91 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1433; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,LeftBank_Nov25,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.41,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,0.000000,99.540758,99.540758,0.560727,0.707463,0.351712,0.910035,0.973472
1,LeftBank_Nov25,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:42:00+00:00,4h 16m after,4.274436,0.000000,100.000000,100.000000,0.728513,0.732571,0.032982,1.000000,1.000000
2,LeftBank_Nov25,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.41,2016-03-21 03:03:00+00:00,4h 37m after,4.624436,0.000000,100.000000,100.000000,0.875331,0.876667,0.024946,1.000000,1.000000
3,LeftBank_Nov25,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.52,2016-04-26 18:10:00+00:00,4h 06m after,4.097786,0.000000,100.000000,100.000000,0.791612,0.810376,0.074151,1.000000,1.000000
4,LeftBank_Nov25,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,0.000000,100.000000,100.000000,0.374865,0.375271,0.360858,0.780712,0.904707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,LeftBank_Nov25,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:11:00+00:00,5h 15m after,5.250285,0.000000,100.000000,100.000000,0.698017,0.700000,0.027931,1.000000,1.000000
180,LeftBank_Nov25,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,0.000000,100.000000,99.885189,0.597252,0.720235,0.288570,0.986207,1.000000
181,LeftBank_Nov25,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.17,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,1.377727,100.000000,100.000000,0.515440,0.546539,0.132425,0.989667,0.996556
182,LeftBank_Nov25,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:19:00+00:00,4h 07m after,4.114174,0.000000,100.000000,100.000000,0.412638,0.404896,0.064709,1.000000,1.000000
183,LeftBank_Nov25,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.47,2025-12-23 18:02:00+00:00,4h 24m after,4.394173,0.000000,100.000000,5.970149,0.451344,0.453535,0.011966,1.000000,1.000000

C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Nov25\LeftBank_Nov25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

LeftBank_Feb26: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 91 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1433; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,LeftBank_Feb26,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.41,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,0.00000,99.54023,99.540230,0.560471,0.707288,0.351860,0.909931,0.973441
1,LeftBank_Feb26,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:42:00+00:00,4h 16m after,4.274436,0.00000,100.00000,100.000000,0.728491,0.732610,0.033011,1.000000,1.000000
2,LeftBank_Feb26,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.41,2016-03-21 03:03:00+00:00,4h 37m after,4.624436,0.00000,100.00000,100.000000,0.875343,0.876627,0.024895,1.000000,1.000000
3,LeftBank_Feb26,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.52,2016-04-26 18:10:00+00:00,4h 06m after,4.097786,0.00000,100.00000,100.000000,0.791722,0.810491,0.074212,1.000000,1.000000
4,LeftBank_Feb26,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,0.00000,100.00000,100.000000,0.375187,0.366774,0.361505,0.780460,0.904598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,LeftBank_Feb26,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:11:00+00:00,5h 15m after,5.250285,0.00000,100.00000,100.000000,0.698152,0.700410,0.027984,1.000000,1.000000
180,LeftBank_Feb26,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,0.00000,100.00000,99.770115,0.595684,0.715752,0.289111,0.986175,1.000000
181,LeftBank_Feb26,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.17,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,1.37931,100.00000,100.000000,0.515317,0.546558,0.132532,0.989655,0.996552
182,LeftBank_Feb26,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:19:00+00:00,4h 07m after,4.114174,0.00000,100.00000,100.000000,0.412926,0.405106,0.064608,1.000000,1.000000
183,LeftBank_Feb26,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.47,2025-12-23 18:02:00+00:00,4h 24m after,4.394173,0.00000,100.00000,6.321839,0.451817,0.453883,0.011859,1.000000,1.000000

C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\LeftBank_Feb26\LeftBank_Feb26_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

Paremata_Nov25: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 92 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1434; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Paremata_Nov25,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.40,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,1.418727,100.0,100.000000,0.413006,0.571266,0.349716,0.839481,0.897041
1,Paremata_Nov25,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:43:00+00:00,4h 17m after,4.291103,1.216052,100.0,100.000000,0.461179,0.557333,0.251845,0.897041,0.920551
2,Paremata_Nov25,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.41,2016-03-21 03:04:00+00:00,4h 38m after,4.641103,0.162140,100.0,100.000000,0.650434,0.754266,0.277856,0.931090,0.948115
3,Paremata_Nov25,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.52,2016-04-26 18:11:00+00:00,4h 05m after,4.081119,2.675314,100.0,100.000000,0.557013,0.698413,0.329849,0.880016,0.901094
4,Paremata_Nov25,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,0.648561,100.0,100.000000,0.402976,0.598811,0.380608,0.761654,0.896230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,Paremata_Nov25,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:11:00+00:00,5h 15m after,5.250285,6.364005,100.0,100.000000,0.534325,0.618090,0.249248,0.923794,0.941630
180,Paremata_Nov25,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,11.390353,100.0,100.000000,0.615119,0.793241,0.350763,0.891366,0.921767
181,Paremata_Nov25,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.16,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,18.038103,100.0,100.000000,0.328593,0.405542,0.211491,0.892177,0.919335
182,Paremata_Nov25,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:19:00+00:00,4h 07m after,4.114174,10.741792,100.0,100.000000,0.394618,0.466667,0.222666,0.899068,0.926632
183,Paremata_Nov25,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.47,2025-12-23 18:02:00+00:00,4h 24m after,4.394173,5.796514,100.0,78.070531,0.320573,0.363329,0.142704,0.936137,0.964174

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Nov25\Paremata_Nov25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

Paremata_Feb26: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 91 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1433; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Paremata_Feb26,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.40,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,2.913328,100.0,100.000000,0.266685,0.230911,0.319687,0.784414,0.873270
1,Paremata_Feb26,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:43:00+00:00,4h 17m after,4.291103,2.257830,100.0,100.000000,0.457745,0.570332,0.276729,0.879825,0.903860
2,Paremata_Feb26,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.41,2016-03-21 03:04:00+00:00,4h 38m after,4.641103,0.436999,100.0,100.000000,0.621129,0.735369,0.288466,0.923525,0.937363
3,Paremata_Feb26,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.52,2016-04-26 18:11:00+00:00,4h 05m after,4.081119,4.078660,100.0,100.000000,0.505851,0.677273,0.346480,0.855062,0.876184
4,Paremata_Feb26,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,1.383831,100.0,100.000000,0.232531,0.094131,0.358265,0.635834,0.857975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,Paremata_Feb26,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:11:00+00:00,5h 15m after,5.250285,9.978150,100.0,100.000000,0.511334,0.609249,0.251757,0.919155,0.937363
180,Paremata_Feb26,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,19.009468,100.0,100.000000,0.569364,0.779141,0.375870,0.871085,0.908958
181,Paremata_Feb26,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.16,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,30.954115,100.0,100.000000,0.302481,0.412823,0.237601,0.865259,0.895849
182,Paremata_Feb26,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:19:00+00:00,4h 07m after,4.114174,17.844137,100.0,100.000000,0.373067,0.458248,0.232155,0.884195,0.915513
183,Paremata_Feb26,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.47,2025-12-23 18:02:00+00:00,4h 24m after,4.394173,9.104151,100.0,60.160233,0.297050,0.347245,0.149196,0.926150,0.955206

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb26\Paremata_Feb26_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

Paremata_Feb25: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 91 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1433; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Paremata_Feb25,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.40,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,2.727273,100.0,100.000000,0.280660,0.249752,0.323256,0.795455,0.882576
1,Paremata_Feb25,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:43:00+00:00,4h 17m after,4.291103,2.121212,100.0,100.000000,0.476288,0.577287,0.264143,0.895455,0.912121
2,Paremata_Feb25,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.41,2016-03-21 03:04:00+00:00,4h 38m after,4.641103,0.303030,100.0,100.000000,0.628661,0.730435,0.270233,0.931818,0.943939
3,Paremata_Feb25,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.52,2016-04-26 18:11:00+00:00,4h 05m after,4.081119,4.545455,100.0,100.000000,0.520884,0.674993,0.328355,0.872727,0.890909
4,Paremata_Feb25,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,1.666667,100.0,100.000000,0.239441,0.094919,0.360604,0.639394,0.865152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,Paremata_Feb25,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:11:00+00:00,5h 15m after,5.250285,10.378788,100.0,100.000000,0.532668,0.619896,0.241994,0.925758,0.943939
180,Paremata_Feb25,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,19.772727,100.0,100.000000,0.592758,0.794493,0.366911,0.885606,0.918182
181,Paremata_Feb25,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.16,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,32.196970,100.0,100.000000,0.317329,0.421632,0.233242,0.881061,0.904545
182,Paremata_Feb25,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:19:00+00:00,4h 07m after,4.114174,18.560606,100.0,100.000000,0.387581,0.460125,0.220919,0.903030,0.927273
183,Paremata_Feb25,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.47,2025-12-23 18:02:00+00:00,4h 24m after,4.394173,10.833333,100.0,60.151515,0.307318,0.356981,0.167324,0.916877,0.942065

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Paremata_Feb25\Paremata_Feb25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

ThePoint_Nov25: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 91 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1433; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,ThePoint_Nov25,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.41,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,2.711864,100.0,99.096045,0.372419,0.396491,0.417034,0.698974,0.830103
1,ThePoint_Nov25,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:42:00+00:00,4h 16m after,4.274436,3.163842,100.0,99.548023,0.531607,0.652561,0.282468,0.909194,0.940976
2,ThePoint_Nov25,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.41,2016-03-21 03:03:00+00:00,4h 37m after,4.624436,0.903955,100.0,99.548023,0.662445,0.784615,0.274168,0.944381,0.970488
3,ThePoint_Nov25,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.52,2016-04-26 18:10:00+00:00,4h 06m after,4.097786,11.073446,100.0,99.096045,0.357761,0.520611,0.403056,0.729761,0.793615
4,ThePoint_Nov25,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,2.033898,100.0,99.548023,0.339218,0.430285,0.397903,0.674234,0.816118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,ThePoint_Nov25,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:11:00+00:00,5h 15m after,5.250285,8.022599,100.0,84.293785,0.504941,0.629781,0.273616,0.914209,0.943700
180,ThePoint_Nov25,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,14.124294,100.0,100.000000,0.438626,0.647590,0.392237,0.784181,0.862147
181,ThePoint_Nov25,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.17,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,14.350282,100.0,100.000000,0.285898,0.457909,0.310446,0.751412,0.822599
182,ThePoint_Nov25,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:19:00+00:00,4h 07m after,4.114174,12.994350,100.0,100.000000,0.253211,0.361274,0.243262,0.811299,0.864407
183,ThePoint_Nov25,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.47,2025-12-23 18:02:00+00:00,4h 24m after,4.394173,21.016949,100.0,85.649718,0.286011,0.354299,0.188607,0.926121,0.968338

C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Nov25\ThePoint_Nov25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

ThePoint_Feb26: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 91 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1433; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,ThePoint_Feb26,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.41,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,2.714932,100.0,99.095023,0.372708,0.399033,0.417185,0.698630,0.829909
1,ThePoint_Feb26,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:42:00+00:00,4h 16m after,4.274436,3.167421,100.0,99.547511,0.532030,0.652843,0.282349,0.909091,0.940909
2,ThePoint_Feb26,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.41,2016-03-21 03:03:00+00:00,4h 37m after,4.624436,0.904977,100.0,99.547511,0.662755,0.784713,0.274170,0.944318,0.970455
3,ThePoint_Feb26,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.52,2016-04-26 18:10:00+00:00,4h 06m after,4.097786,11.085973,100.0,99.095023,0.358137,0.522786,0.403132,0.729452,0.793379
4,ThePoint_Feb26,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,2.036199,100.0,99.547511,0.339476,0.432904,0.398055,0.673864,0.815909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,ThePoint_Feb26,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:11:00+00:00,5h 15m after,5.250285,8.031674,100.0,84.389140,0.504941,0.629781,0.273616,0.914209,0.943700
180,ThePoint_Feb26,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,14.027149,100.0,100.000000,0.439012,0.649681,0.392290,0.783937,0.861991
181,ThePoint_Feb26,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.17,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,14.253394,100.0,100.000000,0.286271,0.458980,0.310423,0.752262,0.822398
182,ThePoint_Feb26,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:19:00+00:00,4h 07m after,4.114174,12.895928,100.0,100.000000,0.253513,0.361360,0.243234,0.812217,0.864253
183,ThePoint_Feb26,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.47,2025-12-23 18:02:00+00:00,4h 24m after,4.394173,21.040724,100.0,85.633484,0.286352,0.354430,0.188497,0.926024,0.968296

C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\ThePoint_Feb26\ThePoint_Feb26_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

Takapuwahia_Nov25: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 92 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1434; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Takapuwahia_Nov25,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.40,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,8.759124,100.0,100.0,0.070676,-0.105006,0.402207,0.408759,0.496350
1,Takapuwahia_Nov25,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:44:00+00:00,4h 18m after,4.307770,7.299270,100.0,100.0,0.254253,0.419355,0.358398,0.708029,0.773723
2,Takapuwahia_Nov25,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.40,2016-03-21 03:04:00+00:00,4h 38m after,4.641103,5.839416,100.0,100.0,0.249016,0.368421,0.406619,0.649635,0.715328
3,Takapuwahia_Nov25,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.51,2016-04-26 18:11:00+00:00,4h 05m after,4.081119,8.759124,100.0,100.0,0.169927,0.257979,0.378313,0.605839,0.656934
4,Takapuwahia_Nov25,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,17.518248,100.0,100.0,-0.061065,-0.225425,0.347896,0.335766,0.357664
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,Takapuwahia_Nov25,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:12:00+00:00,5h 14m after,5.233618,35.766423,100.0,100.0,0.253054,0.468310,0.349970,0.708029,0.773723
180,Takapuwahia_Nov25,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,43.065693,100.0,100.0,0.319685,0.462857,0.426946,0.671533,0.766423
181,Takapuwahia_Nov25,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.16,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,47.445255,100.0,100.0,0.154562,0.364265,0.317123,0.635036,0.693431
182,Takapuwahia_Nov25,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:20:00+00:00,4h 06m after,4.097507,50.364964,100.0,100.0,0.137366,0.298027,0.284745,0.642336,0.737226
183,Takapuwahia_Nov25,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.46,2025-12-23 18:03:00+00:00,4h 23m after,4.377507,56.204380,100.0,100.0,0.135817,0.274912,0.253144,0.715328,0.788321

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Nov25\Takapuwahia_Nov25_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

Takapuwahia_Feb26: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 92 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1434; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,Takapuwahia_Feb26,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.40,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,5.217391,100.0,100.0,0.073763,-0.088608,0.377711,0.417391,0.513043
1,Takapuwahia_Feb26,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:44:00+00:00,4h 18m after,4.307770,3.478261,100.0,100.0,0.277654,0.419355,0.326535,0.730435,0.808696
2,Takapuwahia_Feb26,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.40,2016-03-21 03:04:00+00:00,4h 38m after,4.641103,1.739130,100.0,100.0,0.266671,0.368421,0.377812,0.660870,0.739130
3,Takapuwahia_Feb26,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.51,2016-04-26 18:11:00+00:00,4h 05m after,4.081119,5.217391,100.0,100.0,0.188350,0.297229,0.353485,0.626087,0.678261
4,Takapuwahia_Feb26,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,15.652174,100.0,100.0,-0.065127,-0.223602,0.305148,0.330435,0.356522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,Takapuwahia_Feb26,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:12:00+00:00,5h 14m after,5.233618,34.782609,100.0,100.0,0.276235,0.468310,0.321090,0.730435,0.808696
180,Takapuwahia_Feb26,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,43.478261,100.0,100.0,0.342742,0.462857,0.394336,0.704348,0.800000
181,Takapuwahia_Feb26,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.16,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,44.347826,100.0,100.0,0.173359,0.364265,0.294909,0.652174,0.713043
182,Takapuwahia_Feb26,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:20:00+00:00,4h 06m after,4.097507,47.826087,100.0,100.0,0.153722,0.298027,0.254769,0.652174,0.765217
183,Takapuwahia_Feb26,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.46,2025-12-23 18:03:00+00:00,4h 23m after,4.377507,54.782609,100.0,100.0,0.156627,0.276956,0.218269,0.739130,0.826087

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\Takapuwahia_Feb26\Takapuwahia_Feb26_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

IveyBay_ThePoint_LeftBank_Oct24: search 2016-2025 Sentinel-2 scenes
  2016: 51 STAC items
  2017: 91 STAC items
  2018: 143 STAC items
  2019: 137 STAC items
  2020: 142 STAC items
  2021: 151 STAC items
  2022: 187 STAC items
  2023: 245 STAC items
  2024: 145 STAC items
  2025: 141 STAC items
  STAC items across range: 1433; under cloud cutoff: 204
  Saved 184 scene records to C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_rgb_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_scl_by_dry_area.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_rgb_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_scl_by_mean_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_rgb_by_median_mndwi.html
  Saved C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_scl_by_median_mndwi.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html

,site,date,satellite_time_utc,cloud_cover_pct,nearest_low_tide_height_msl,nearest_low_tide_time_utc,time_from_low_tide,hours_from_low_tide,dry_area_pct,scl_coverage_pct,valid_scl_pct,mean_mndwi,median_mndwi,std_mndwi,fraction_mndwi_gt_0,fraction_mndwi_gt_-0.1
0,IveyBay_ThePoint_LeftBank_Oct24,2016-01-30,2016-01-30 22:25:32.030000+00:00,5.350440,-0.41,2016-01-30 19:30:00+00:00,2h 56m after,2.925564,2.391726,100.0,99.095023,0.485859,0.691781,0.411078,0.793216,0.868232
1,IveyBay_ThePoint_LeftBank_Oct24,2016-02-19,2016-02-19 22:25:32.029000+00:00,4.123013,-0.34,2016-02-20 02:42:00+00:00,4h 16m after,4.274436,3.038138,100.0,98.836458,0.554689,0.688385,0.288915,0.904513,0.937214
2,IveyBay_ThePoint_LeftBank_Oct24,2016-03-20,2016-03-20 22:25:32.030000+00:00,1.542679,-0.41,2016-03-21 03:03:00+00:00,4h 37m after,4.624436,0.904977,100.0,99.547511,0.666901,0.797945,0.306073,0.928571,0.953896
3,IveyBay_ThePoint_LeftBank_Oct24,2016-04-26,2016-04-26 22:15:52.028000+00:00,8.144639,-0.52,2016-04-26 18:10:00+00:00,4h 06m after,4.097786,5.688429,100.0,99.482870,0.512111,0.715596,0.386382,0.825211,0.859649
4,IveyBay_ThePoint_LeftBank_Oct24,2016-04-29,2016-04-29 22:25:42.029000+00:00,1.199144,-0.31,2016-04-29 20:26:00+00:00,2h 00m after,1.995008,2.262443,100.0,99.612153,0.367431,0.502500,0.378949,0.750811,0.837119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,IveyBay_ThePoint_LeftBank_Oct24,2025-09-09,2025-09-09 22:26:01.025000+00:00,6.096213,-0.71,2025-09-09 17:11:00+00:00,5h 15m after,5.250285,10.859729,100.0,100.000000,0.525911,0.651934,0.283713,0.899160,0.929541
180,IveyBay_ThePoint_LeftBank_Oct24,2025-09-14,2025-09-14 22:25:39.024000+00:00,1.723290,-0.24,2025-09-14 20:09:00+00:00,2h 17m after,2.277507,11.700065,100.0,100.000000,0.545448,0.766467,0.383479,0.850679,0.893342
181,IveyBay_ThePoint_LeftBank_Oct24,2025-10-29,2025-10-29 22:26:01.025000+00:00,4.607227,-0.17,2025-10-29 20:38:00+00:00,1h 48m after,1.800285,12.863607,100.0,100.000000,0.362516,0.498024,0.286018,0.827408,0.878474
182,IveyBay_ThePoint_LeftBank_Oct24,2025-12-08,2025-12-08 22:25:51.025000+00:00,4.890863,-0.46,2025-12-08 18:19:00+00:00,4h 07m after,4.114174,10.859729,100.0,100.000000,0.298707,0.372515,0.233158,0.853264,0.890756
183,IveyBay_ThePoint_LeftBank_Oct24,2025-12-23,2025-12-23 22:25:39.024000+00:00,7.287385,-0.47,2025-12-23 18:02:00+00:00,4h 24m after,4.394173,19.521655,100.0,57.142857,0.208074,0.199279,0.203907,0.847285,0.936652

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_rgb_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_scl_by_dry_area.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_rgb_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_scl_by_mean_mndwi.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2016-2025_low_cloud_mean_mndwi_vs_low_tide.html