# All-Site Low-Tide Exposure

For each site and each year from 2022 through 2025, keep Sentinel-2 scenes with catalogue cloud cover below 10%. Record the nearest predicted low tide within 3 hours and calculate dry area as SCL 4+5 pixels divided by the full rasterized site area. Save each site's CSV, RGB/SCL galleries, and dry-area scatter only in that site's folder.

In [1]:
import base64
import calendar
import html as html_module
import io
import os
import pathlib
import sys

import dotenv
import geopandas
import matplotlib.pyplot as plt
import numpy
import odc.stac
import pandas
import planetary_computer
import plotly.express as px
import rasterio.features
import requests
import xarray
from IPython.display import FileLink, display

working_path = pathlib.Path.cwd().resolve()
module_path = working_path / "scripts" if (working_path / "scripts").is_dir() else working_path.parent / "scripts"
if not module_path.is_dir():
    raise FileNotFoundError(f"Could not find the scripts directory from {working_path}")
if str(module_path) not in sys.path:
    sys.path.insert(0, str(module_path))

import sentinel2
import utils

data_path = utils.get_data_path()
site_polygons_path = data_path / "site_polygons"
output_path = data_path / "analysis" / "all_sites_tide_exposure"
output_path.mkdir(parents=True, exist_ok=True)

dotenv.load_dotenv()
tide_api_key = os.environ.get("TIDE_API")
if not tide_api_key:
    raise ValueError("Set TIDE_API in the environment or project .env file before querying tides.")

print(f"Site polygons: {site_polygons_path}")
print(f"Output root: {output_path}")

Site polygons: C:\Local\repos\seagrass-detection\data\site_polygons
Output root: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure

## Survey Settings

The notebook processes the inclusive year range below. Every Sentinel-2 scene under the catalogue cloud cutoff is retained; a 3-hour line in each scatter marks the low-tide context window.

In [2]:
YEAR_START = 2022
YEAR_END = 2025
YEAR_RANGE = f"{YEAR_START}-{YEAR_END}"
MAX_ITEMS_PER_YEAR = 400
MAX_CLOUD_COVER_PCT = 10.0
CANDIDATE_WINDOW_HRS = 4.0
TIDE_SEARCH_RADIUS_HRS = 12
LOCAL_TIME_ZONE = "Pacific/Auckland"
OUTPUT_REVISION = "lowtide-duration-v4"

site_polygon_files = sorted(site_polygons_path.glob("*_polygon.gpkg"))
if not site_polygon_files:
    raise FileNotFoundError(f"No site polygons found under {site_polygon_files}")
site_names = [path.stem.removesuffix("_polygon") for path in site_polygon_files]

print(f"Year range: {YEAR_RANGE}; sites: {len(site_polygon_files)}")
print(f"STAC max_items per year/site: {MAX_ITEMS_PER_YEAR}")
print(f"Catalogue cloud cutoff: <{MAX_CLOUD_COVER_PCT:g}%")
print(f"Low-tide reference range: +/-{CANDIDATE_WINDOW_HRS:g} hours")

Year range: 2022-2025; sites: 20
STAC max_items per year/site: 400
Catalogue cloud cutoff: <10%
Low-tide reference range: +/-3 hours

## Tide Event Helpers

Fetch NIWA high/low events in requests of at most 31 days, cache by site and month, and calculate the nearest low event, signed offset, and formatted duration.

In [3]:
def fetch_tide_values(start_date, number_of_days, latitude, longitude):
    if not 1 <= number_of_days <= 31:
        raise ValueError("NIWA tide requests must cover between 1 and 31 days.")
    response = requests.get(
        sentinel2.TIDE_API_STUB,
        params={
            "lat": latitude,
            "long": longitude,
            "datum": "MSL",
            "numberOfDays": number_of_days,
            "apikey": tide_api_key,
            "startDate": start_date.strftime("%Y-%m-%d"),
        },
        timeout=30,
    )
    response.raise_for_status()
    tide_data = pandas.DataFrame.from_records(response.json().get("values", []))
    if tide_data.empty:
        return tide_data
    tide_data["time"] = pandas.to_datetime(tide_data["time"], utc=True)
    tide_data["value"] = pandas.to_numeric(tide_data["value"], errors="raise")
    return tide_data


def tide_predictions_for_month(timestamp_utc, latitude, longitude, tide_cache):
    timestamp_utc = pandas.Timestamp(timestamp_utc)
    timestamp_utc = (
        timestamp_utc.tz_localize("UTC")
        if timestamp_utc.tzinfo is None
        else timestamp_utc.tz_convert("UTC")
    )
    month_start = timestamp_utc.normalize().replace(day=1)
    request_start = month_start - pandas.Timedelta(days=1)
    requested_days = calendar.monthrange(month_start.year, month_start.month)[1] + 2
    cache_key = (latitude, longitude, month_start.strftime("%Y-%m"))
    if cache_key not in tide_cache:
        first_days = min(requested_days, 31)
        tide_parts = [fetch_tide_values(request_start, first_days, latitude, longitude)]
        if requested_days > first_days:
            overlap_days = 1
            next_start = request_start + pandas.Timedelta(days=first_days - overlap_days)
            next_days = requested_days - first_days + overlap_days
            tide_parts.append(fetch_tide_values(next_start, next_days, latitude, longitude))
        tide_data = pandas.concat(tide_parts, ignore_index=True)
        if tide_data.empty:
            raise ValueError(f"NIWA returned no tide events for {month_start:%Y-%m}.")
        tide_cache[cache_key] = (
            tide_data.sort_values("time").drop_duplicates("time", keep="last").reset_index(drop=True)
        )
    return tide_cache[cache_key]


def nearest_low_tide(timestamp_utc, tide_data):
    timestamp_utc = pandas.Timestamp(timestamp_utc)
    timestamp_utc = (
        timestamp_utc.tz_localize("UTC")
        if timestamp_utc.tzinfo is None
        else timestamp_utc.tz_convert("UTC")
    )
    search_window = tide_data[
        tide_data["time"].between(
            timestamp_utc - pandas.Timedelta(hours=TIDE_SEARCH_RADIUS_HRS),
            timestamp_utc + pandas.Timedelta(hours=TIDE_SEARCH_RADIUS_HRS),
        )
    ].copy()
    if search_window.empty:
        raise ValueError(f"No NIWA tide events near {timestamp_utc}.")
    is_local_minimum = (tide_data["value"] <= tide_data["value"].shift(1)) & (
        tide_data["value"] <= tide_data["value"].shift(-1)
    )
    low_points = tide_data.loc[
        is_local_minimum & tide_data["time"].isin(search_window["time"])
    ]
    if low_points.empty:
        low_event = search_window.nsmallest(1, "value").iloc[0]
    else:
        low_index = (low_points["time"] - timestamp_utc).abs().idxmin()
        low_event = low_points.loc[low_index]
    hours_from_low = (timestamp_utc - low_event["time"]).total_seconds() / 3600
    total_minutes = int(round(abs(hours_from_low) * 60))
    hours, minutes = divmod(total_minutes, 60)
    direction = "at" if total_minutes == 0 else "before" if hours_from_low < 0 else "after"
    nearest_event = tide_data.loc[(tide_data["time"] - timestamp_utc).abs().idxmin()]
    return {
        "tide_height_msl": float(nearest_event["value"]),
        "nearest_low_tide_time_utc": low_event["time"],
        "nearest_low_tide_height_msl": float(low_event["value"]),
        "hours_from_low_tide": hours_from_low,
        "duration_from_low_tide": f"{hours}h {minutes:02d}m {direction}",
    }

## Process Each Site

All scenes meeting the cloud-cover cutoff are measured; low tide is recorded as context and does not exclude scenes.

In [4]:
def analyze_site(site_polygon_file):
    site_name = site_polygon_file.stem.removesuffix("_polygon")
    site_output_dir = output_path / site_name
    site_output_dir.mkdir(parents=True, exist_ok=True)
    print(f"\n{site_name}: search {YEAR_RANGE}")

    site_polygon = geopandas.read_file(site_polygon_file)
    if site_polygon.crs is None or site_polygon.empty:
        raise ValueError(f"Site polygon must be non-empty and have a CRS: {site_polygon_file}")
    polygon_wgs84 = site_polygon.to_crs(utils.CRS_WSG)
    centroid = polygon_wgs84.geometry.union_all().centroid
    latitude, longitude = float(centroid.y), float(centroid.x)
    search_geometry = site_polygon.buffer(sentinel2.S2_RESOLUTION).to_crs(utils.CRS_WSG)

    items_by_id = {}
    cloud_by_date = {}
    for year in range(YEAR_START, YEAR_END + 1):
        search_results = sentinel2.stac_search_with_retry(
            url=sentinel2.CATALOGUE_URL,
            max_items=MAX_ITEMS_PER_YEAR,
            collections=[sentinel2.COLLECTION],
            bbox=search_geometry.total_bounds,
            datetime=f"{year}-01-01/{year}-12-31",
            sortby=[{"field": "properties.eo:cloud_cover", "direction": "asc"}],
            get_collection=True,
        )
        for item in search_results.items:
            raw_cloud_cover = item.properties.get("eo:cloud_cover")
            if raw_cloud_cover is None:
                continue
            cloud_cover = float(raw_cloud_cover)
            if cloud_cover >= MAX_CLOUD_COVER_PCT:
                continue
            acquisition_time = pandas.to_datetime(item.properties["datetime"], utc=True)
            scene_date = acquisition_time.strftime("%Y-%m-%d")
            items_by_id[item.id] = item
            current_cloud_cover = cloud_by_date.get(scene_date)
            if current_cloud_cover is None or cloud_cover < current_cloud_cover:
                cloud_by_date[scene_date] = cloud_cover

    print(f"  Distinct cloud-filtered dates: {len(cloud_by_date)}")
    if not items_by_id:
        print(f"  No scenes below {MAX_CLOUD_COVER_PCT:g}% cloud cover")
        return pandas.DataFrame()

    satellite_data = odc.stac.load(
        list(items_by_id.values()),
        bbox=search_geometry.total_bounds,
        bands=sentinel2.RGB_BANDS + ["SCL"],
        chunks={},
        groupby="solar_day",
        resolution=sentinel2.S2_RESOLUTION,
        dtype="uint16",
        nodata=0,
        patch_url=planetary_computer.sign,
    )
    satellite_data = satellite_data.rio.clip(
        site_polygon.to_crs(satellite_data.rio.crs).geometry,
        all_touched=True,
        drop=True,
    ).load()
    if satellite_data.sizes.get("time", 0) == 0:
        print("  No selected scenes intersect the site polygon")
        return pandas.DataFrame()

    site_polygon_projected = site_polygon.to_crs(satellite_data.rio.crs)
    site_mask_values = rasterio.features.geometry_mask(
        [geometry.__geo_interface__ for geometry in site_polygon_projected.geometry],
        out_shape=(satellite_data.sizes["y"], satellite_data.sizes["x"]),
        transform=satellite_data.rio.transform(),
        invert=True,
        all_touched=True,
    )
    site_mask = xarray.DataArray(
        site_mask_values,
        coords={"y": satellite_data["y"], "x": satellite_data["x"]},
        dims=("y", "x"),
    )
    site_pixel_count = int(site_mask.sum())
    if site_pixel_count == 0:
        raise ValueError(f"No raster pixels fall inside {site_polygon_file}")

    scl = satellite_data["SCL"]
    dry_pixels = (scl.isin([4, 5]) & site_mask).sum(dim=["x", "y"]).compute()
    scl_coverage = ((scl > 0) & site_mask).sum(dim=["x", "y"]).compute()
    scene_dates = satellite_data.time.dt.strftime("%Y-%m-%d").values.tolist()
    tide_cache = {}
    records = []
    for scene_index, scene_date in enumerate(scene_dates):
        timestamp = pandas.Timestamp(satellite_data.time.isel(time=scene_index).values)
        timestamp = timestamp.tz_localize("UTC") if timestamp.tzinfo is None else timestamp.tz_convert("UTC")
        tide_data = tide_predictions_for_month(timestamp, latitude, longitude, tide_cache)
        low_tide = nearest_low_tide(timestamp, tide_data)
        n_dry = int(dry_pixels.isel(time=scene_index))
        n_covered = int(scl_coverage.isel(time=scene_index))
        records.append({
            "site": site_name,
            "date": scene_date,
            "year": int(scene_date[:4]),
            "satellite_time_utc": timestamp,
            "cloud_cover_pct": cloud_by_date.get(scene_date, numpy.nan),
            "nearest_low_tide_time_utc": low_tide["nearest_low_tide_time_utc"],
            "nearest_low_tide_height_msl": low_tide["nearest_low_tide_height_msl"],
            "hours_from_low_tide": low_tide["hours_from_low_tide"],
            "duration_from_low_tide": low_tide["duration_from_low_tide"],
            "dry_pixels_scl_4_5": n_dry,
            "dry_area_pct": 100 * n_dry / site_pixel_count,
            "scl_coverage_pct": 100 * n_covered / site_pixel_count,
            "site_pixels": site_pixel_count,
        })

    site_data = pandas.DataFrame.from_records(records).sort_values("satellite_time_utc").reset_index(drop=True)
    site_csv = site_output_dir / f"{site_name}_{YEAR_RANGE}_dry_area_{OUTPUT_REVISION}.csv"
    site_data.to_csv(site_csv, index=False)
    print(f"  Saved {len(site_data)} scene rows: {site_csv}")

    scl_classes = [
        (0, "No data", "#000000"),
        (1, "Saturated/defective", "#ff0000"),
        (2, "Dark area", "#2f2f2f"),
        (3, "Cloud shadow", "#643200"),
        (4, "Vegetation", "#00a000"),
        (5, "Not vegetated", "#ffe65a"),
        (6, "Water", "#0000ff"),
        (7, "Unclassified", "#808080"),
        (8, "Cloud, medium probability", "#c0c0c0"),
        (9, "Cloud, high probability", "#ffffff"),
        (10, "Thin cirrus", "#64c8ff"),
        (11, "Snow/ice", "#ff96ff"),
    ]
    scl_legend = "".join(
        f'<span class="legend-item"><i style="background:{color}"></i>{code}: '
        f'{html_module.escape(label)}</span>'
        for code, label, color in scl_classes
    )
    rgb_cards = []
    scl_cards = []
    for scene_index, row in site_data.iterrows():
        scene_date = html_module.escape(str(row["date"]))
        low_local = pandas.Timestamp(row["nearest_low_tide_time_utc"]).tz_convert(LOCAL_TIME_ZONE)
        caption = (
            f"Dry Area: {row['dry_area_pct']:.1f}%<br>"
            f"Low {low_local:%d %b %H:%M} | {row['duration_from_low_tide']} | "
            f"{row['nearest_low_tide_height_msl']:.2f} m MSL"
        )
        rgb = numpy.stack(
            [satellite_data[band].isel(time=scene_index).values for band in sentinel2.RGB_BANDS],
            axis=-1,
        ).astype(numpy.float32)
        rgb_valid = numpy.isfinite(rgb).all(axis=-1) & (rgb > 0).all(axis=-1)
        rgb_display = numpy.ones_like(rgb)
        if rgb_valid.any():
            for channel in range(3):
                pixels = rgb[..., channel][rgb_valid]
                low, high = numpy.percentile(pixels, [2, 98])
                if high > low:
                    rgb_display[..., channel] = numpy.clip(
                        (rgb[..., channel] - low) / (high - low), 0, 1
                    )
        rgb_display[~rgb_valid] = 1
        rgb_buffer = io.BytesIO()
        rgb_figure, rgb_axis = plt.subplots(figsize=(5, 3.75))
        rgb_axis.imshow(rgb_display)
        rgb_axis.axis("off")
        rgb_figure.savefig(
            rgb_buffer, format="jpg", dpi=90, bbox_inches="tight", pad_inches=0,
            pil_kwargs={"quality": 84, "optimize": True},
        )
        plt.close(rgb_figure)
        rgb_encoded = base64.b64encode(rgb_buffer.getvalue()).decode("ascii")
        rgb_cards.append(
            f'<article class="scene"><h2>{scene_date}</h2>'
            f'<img src="data:image/jpeg;base64,{rgb_encoded}" alt="{site_name} RGB {scene_date}">' 
            f'<div class="caption">{caption}</div></article>'
        )

        scl_array = satellite_data["SCL"].isel(time=scene_index).values
        scl_rgb = numpy.full((*scl_array.shape, 3), 238, dtype=numpy.uint8)
        for class_code, _, color in scl_classes:
            color_rgb = tuple(int(color[index:index + 2], 16) for index in (1, 3, 5))
            scl_rgb[(scl_array == class_code) & site_mask_values] = color_rgb
        scl_buffer = io.BytesIO()
        scl_figure, scl_axis = plt.subplots(figsize=(5, 3.75))
        scl_axis.imshow(scl_rgb)
        scl_axis.axis("off")
        scl_figure.savefig(
            scl_buffer, format="jpg", dpi=90, bbox_inches="tight", pad_inches=0,
            pil_kwargs={"quality": 90, "optimize": True},
        )
        plt.close(scl_figure)
        scl_encoded = base64.b64encode(scl_buffer.getvalue()).decode("ascii")
        scl_cards.append(
            f'<article class="scene"><h2>{scene_date}</h2>'
            f'<img src="data:image/jpeg;base64,{scl_encoded}" alt="{site_name} SCL {scene_date}">' 
            f'<div class="caption">{caption}</div></article>'
        )

    gallery_css = """
:root { color-scheme: light; font-family: "Segoe UI", sans-serif; color: #202a33; background: #f3f5f6; }
body { margin: 0; padding: 20px; }
header, .gallery, .legend { max-width: 1500px; margin: 0 auto 16px; }
h1 { margin: 0 0 6px; font-size: 22px; }
p { margin: 0; color: #56616b; }
.gallery { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(320px, 100%), 1fr)); gap: 14px; }
.scene { min-width: 0; overflow: hidden; background: white; border: 1px solid #d5dce1; border-radius: 5px; }
.scene h2 { margin: 10px 12px 0; font-size: 15px; }
.scene img { display: block; width: 100%; aspect-ratio: 4 / 3; object-fit: contain; background: #f7f8f8; }
.caption { padding: 8px 12px 11px; font-size: 12px; line-height: 1.4; }
.legend { display: flex; flex-wrap: wrap; gap: 6px 12px; padding: 10px; background: white; border: 1px solid #d5dce1; }
.legend-item { display: inline-flex; align-items: center; gap: 5px; font-size: 11px; }
.legend-item i { display: inline-block; width: 14px; height: 14px; border: 1px solid #7b858c; }
@media (max-width: 600px) { body { padding: 10px; } }
"""

    def write_gallery(gallery_title, cards, output_file, legend_html=""):
        page = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html_module.escape(site_name)} {YEAR_RANGE} {html_module.escape(gallery_title)}</title>
<style>{gallery_css}</style></head><body>
<header><h1>{html_module.escape(site_name)}: {YEAR_RANGE} {html_module.escape(gallery_title)}</h1>
<p>{len(cards)} scenes; catalogue cloud cover under {MAX_CLOUD_COVER_PCT:g}%.</p></header>
{legend_html}<main class="gallery">{''.join(cards)}</main></body></html>"""
        output_file.write_text(page, encoding="utf-8")
        print(f"  Saved gallery: {output_file}")

    rgb_gallery_file = site_output_dir / f"{site_name}_{YEAR_RANGE}_rgb_{OUTPUT_REVISION}.html"
    scl_gallery_file = site_output_dir / f"{site_name}_{YEAR_RANGE}_scl_{OUTPUT_REVISION}.html"
    write_gallery("RGB", rgb_cards, rgb_gallery_file)
    write_gallery("SCL", scl_cards, scl_gallery_file, f'<div class="legend">{scl_legend}</div>')

    scatter_data = site_data.copy()
    scatter_data["abs_hours_from_low_tide"] = scatter_data["hours_from_low_tide"].abs()
    scatter_data["date_color"] = pandas.to_datetime(
        scatter_data["satellite_time_utc"], utc=True
    ).astype("int64") / 1e9
    color_ticks = numpy.linspace(scatter_data["date_color"].min(), scatter_data["date_color"].max(), 5)
    color_tick_labels = pandas.to_datetime(color_ticks, unit="s", utc=True).strftime("%d %b %Y").tolist()
    scatter = px.scatter(
        scatter_data,
        x="abs_hours_from_low_tide",
        y="dry_area_pct",
        color="date_color",
        color_continuous_scale="Viridis",
        hover_name="date",
        custom_data=["duration_from_low_tide"],
        labels={
            "abs_hours_from_low_tide": "Absolute hours from low tide",
            "dry_area_pct": "Dry area (% of full site)",
            "date_color": "Acquisition date",
        },
        title=f"{site_name}: Dry Area vs Low-Tide Duration ({YEAR_RANGE})",
    )
    scatter.update_traces(
        marker={"size": 10, "opacity": 0.85, "line": {"width": 0.6, "color": "white"}},
        hovertemplate=(
            "<b>%{hovertext}</b><br>"
            "Dry Area: %{y:.1f}%<br>"
            "Duration from low tide: %{customdata[0]}<extra></extra>"
        ),
    )
    scatter.update_layout(
        height=650,
        hovermode="closest",
        coloraxis_colorbar={
            "title": "Acquisition date",
            "tickvals": color_ticks.tolist(),
            "ticktext": color_tick_labels,
        },
        yaxis={"range": [0, 100]},
    )
    scatter.add_vline(
        x=CANDIDATE_WINDOW_HRS,
        line_dash="dot",
        line_color="#b23a48",
        annotation_text="3-hour range",
        annotation_position="top left",
    )
    scatter_file = site_output_dir / f"{site_name}_{YEAR_RANGE}_dry_vs_low_tide_{OUTPUT_REVISION}.html"
    scatter.write_html(scatter_file, include_plotlyjs=True, auto_open=False)
    print(f"  Saved scatter: {scatter_file}")
    return site_data

## Process All Sites

Sites run sequentially. Per-site CSVs and plots are stored in each site's folder; the aggregate CSV is stored at the analysis root.

In [5]:
site_results = {}
site_errors = []
for site_polygon_file in site_polygon_files:
    site_name = site_polygon_file.stem.removesuffix("_polygon")
    try:
        site_data = analyze_site(site_polygon_file)
        if site_data.empty:
            print(f"{site_name}: no scenes met the cloud cutoff")
            continue
        site_results[site_name] = site_data
        display(site_data.sort_values("dry_area_pct", ascending=False))
    except Exception as error:
        site_errors.append({"site": site_name, "error": str(error)})
        print(f"  ERROR for {site_name}: {error}")

print(f"\nCompleted {len(site_results)} of {len(site_polygon_files)} sites.")
if site_errors:
    print("Sites with errors:")
    display(pandas.DataFrame.from_records(site_errors))

print("Per-site outputs:")
for site_name in site_results:
    site_output_dir = output_path / site_name
    for output_file in sorted(site_output_dir.iterdir()):
        display(FileLink(str(output_file)))

CatlinsLake: search 2022-2025
  Distinct cloud-filtered dates: 45
  Saved 45 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsLake\CatlinsLake_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsLake\CatlinsLake_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsLake\CatlinsLake_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsLake\CatlinsLake_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
25,CatlinsLake,2023-08-29,2023,2023-08-29 22:37:19.024000+00:00,0.054977,2023-08-29 19:27:00+00:00,-1.08,3.171951,3h 10m after,6737,15.197040,100.000000,44331
35,CatlinsLake,2024-08-30,2024,2024-08-30 22:25:49.024000+00:00,1.864714,2024-08-30 18:31:00+00:00,-0.76,3.913618,3h 55m after,6526,14.721076,100.000000,44331
36,CatlinsLake,2024-09-29,2024,2024-09-29 22:25:49.024000+00:00,0.005375,2024-09-29 18:51:00+00:00,-0.76,3.580284,3h 35m after,5235,11.808892,100.000000,44331
26,CatlinsLake,2023-09-08,2023,2023-09-08 22:37:09.024000+00:00,2.688654,2023-09-08 16:15:00+00:00,-0.63,6.369173,6h 22m after,5151,11.619409,100.000000,44331
40,CatlinsLake,2025-04-10,2025,2025-04-10 22:37:09.024000+00:00,4.059831,2025-04-10 19:39:00+00:00,-0.83,2.969173,2h 58m after,4510,10.173468,100.000000,44331
42,CatlinsLake,2025-09-07,2025,2025-09-07 22:37:09.024000+00:00,2.634845,2025-09-07 20:34:00+00:00,-1.01,2.052507,2h 03m after,4400,9.925334,100.000000,44331
20,CatlinsLake,2023-05-03,2023,2023-05-03 22:25:41.024000+00:00,2.077316,2023-05-03 19:30:00+00:00,-0.81,2.928062,2h 56m after,4392,9.907288,100.000000,44331
19,CatlinsLake,2023-03-07,2023,2023-03-07 22:37:01.024000+00:00,0.314562,2023-03-07 21:24:00+00:00,-0.81,1.216951,1h 13m after,4376,9.871196,100.000000,44331
9,CatlinsLake,2022-09-10,2022,2022-09-10 22:25:49.024000+00:00,3.049057,2022-09-10 20:57:00+00:00,-1.09,1.480284,1h 29m after,4337,9.783222,100.000000,44331
21,CatlinsLake,2023-05-06,2023,2023-05-06 22:37:11.024000+00:00,0.689979,2023-05-06 21:32:00+00:00,-0.88,1.086396,1h 05m after,4337,9.783222,99.990977,44331
4,CatlinsLake,2022-03-29,2022,2022-03-29 22:25:51.024000+00:00,2.794599,2022-03-29 19:14:00+00:00,-0.96,3.197507,3h 12m after,4278,9.650132,100.000000,44331
27,CatlinsLake,2023-09-18,2023,2023-09-18 22:37:09.024000+00:00,0.523392,2023-09-18 23:14:00+00:00,-0.66,-0.614160,0h 37m before,4228,9.537344,100.000000,44331
43,CatlinsLake,2025-10-09,2025,2025-10-09 22:26:01.025000+00:00,0.998645,2025-10-09 22:47:00+00:00,-1.02,-0.349715,0h 21m before,4098,9.244096,100.000000,44331
23,CatlinsLake,2023-07-20,2023,2023-07-20 22:37:19.024000+00:00,2.092111,2023-07-20 23:01:00+00:00,-0.70,-0.394716,0h 24m before,3867,8.723015,100.000000,44331
33,CatlinsLake,2024-03-18,2024,2024-03-18 22:25:41.024000+00:00,9.392896,2024-03-18 16:37:00+00:00,-0.64,5.811396,5h 49m after,3831,8.641808,100.000000,44331
0,CatlinsLake,2022-02-20,2022,2022-02-20 22:37:11.024000+00:00,0.005655,2022-02-21 00:00:00+00:00,-0.82,-1.380271,1h 23m before,3824,8.626018,100.000000,44331
5,CatlinsLake,2022-05-03,2022,2022-05-03 22:25:39.024000+00:00,0.003425,2022-05-03 23:00:00+00:00,-0.72,-0.572493,0h 34m before,3692,8.328258,99.774424,44331
24,CatlinsLake,2023-08-21,2023,2023-08-21 22:25:51.024000+00:00,0.002335,2023-08-22 00:29:00+00:00,-0.58,-2.052493,2h 03m before,3620,8.165843,100.000000,44331
22,CatlinsLake,2023-06-20,2023,2023-06-20 22:37:09.024000+00:00,0.570483,2023-06-20 22:47:00+00:00,-0.73,-0.164160,0h 10m before,3347,7.550021,100.000000,44331
8,CatlinsLake,2022-07-22,2022,2022-07-22 22:25:49.024000+00:00,4.431167,2022-07-22 16:34:00+00:00,-0.70,5.863618,5h 52m after,3069,6.922921,99.882701,44331
6,CatlinsLake,2022-05-18,2022,2022-05-18 22:25:51.024000+00:00,1.570445,2022-05-18 23:02:00+00:00,-1.00,-0.602493,0h 36m before,2901,6.543953,99.860143,44331
29,CatlinsLake,2023-11-24,2023,2023-11-24 22:25:39.024000+00:00,0.007616,2023-11-24 18:35:00+00:00,-0.93,3.844173,3h 51m after,2874,6.483048,100.000000,44331
32,CatlinsLake,2024-03-01,2024,2024-03-01 22:37:11.024000+00:00,5.589534,2024-03-02 01:15:00+00:00,-0.54,-2.630271,2h 38m before,2812,6.343191,99.990977,44331
28,CatlinsLake,2023-11-09,2023,2023-11-09 22:25:41.024000+00:00,8.020958,2023-11-09 18:17:00+00:00,-0.66,4.144729,4h 09m after,2670,6.022873,100.000000,44331
2,CatlinsLake,2022-03-22,2022,2022-03-22 22:37:11.024000+00:00,0.702350,2022-03-23 00:29:00+00:00,-0.84,-1.863604,1h 52m before,2653,5.984526,99.972931,44331
18,CatlinsLake,2023-02-27,2023,2023-02-27 22:25:49.025000+00:00,0.000676,2023-02-28 03:38:00+00:00,-0.62,-5.203049,5h 12m before,2473,5.578489,100.000000,44331
30,CatlinsLake,2023-12-27,2023,2023-12-27 22:37:09.024000+00:00,3.575572,2023-12-27 21:37:00+00:00,-0.82,1.002507,1h 00m after,2396,5.404796,100.000000,44331
13,CatlinsLake,2023-01-01,2023,2023-01-01 22:37:09.024000+00:00,4.210165,2023-01-01 17:11:00+00:00,-0.71,5.435840,5h 26m after,2360,5.323588,100.000000,44331
38,CatlinsLake,2024-12-16,2024,2024-12-16 22:37:11.024000+00:00,0.032594,2024-12-16 22:03:00+00:00,-0.94,0.569729,0h 34m after,2296,5.179220,100.000000,44331
3,CatlinsLake,2022-03-24,2022,2022-03-24 22:25:39.024000+00:00,0.352983,2022-03-25 02:35:00+00:00,-0.76,-4.155827,4h 09m before,2260,5.098013,100.000000,44331
7,CatlinsLake,2022-06-05,2022,2022-06-05 22:37:09.024000+00:00,4.496783,2022-06-06 01:37:00+00:00,-0.53,-2.997493,3h 00m before,2216,4.998759,99.314250,44331
39,CatlinsLake,2025-01-05,2025,2025-01-05 22:37:11.024000+00:00,4.852486,2025-01-06 01:45:00+00:00,-0.84,-3.130271,3h 08m before,2170,4.894994,100.000000,44331
41,CatlinsLake,2025-06-16,2025,2025-06-16 22:25:39.024000+00:00,5.443942,2025-06-17 00:59:00+00:00,-0.71,-2.555827,2h 33m before,2139,4.825066,100.000000,44331
34,CatlinsLake,2024-07-14,2024,2024-07-14 22:37:09.024000+00:00,2.341420,2024-07-15 03:52:00+00:00,-0.49,-5.247493,5h 15m before,2089,4.712278,99.271390,44331
11,CatlinsLake,2022-12-24,2022,2022-12-24 22:25:41.024000+00:00,2.224449,2022-12-24 22:03:00+00:00,-1.05,0.378062,0h 23m after,2083,4.698744,100.000000,44331
14,CatlinsLake,2023-01-08,2023,2023-01-08 22:25:39.024000+00:00,0.001505,2023-01-08 22:31:00+00:00,-0.73,-0.089160,0h 05m before,1957,4.414518,100.000000,44331
12,CatlinsLake,2022-12-27,2022,2022-12-27 22:37:11.024000+00:00,0.739290,2022-12-28 00:54:00+00:00,-0.97,-2.280271,2h 17m before,1926,4.344590,100.000000,44331
15,CatlinsLake,2023-01-18,2023,2023-01-18 22:25:39.024000+00:00,0.224217,2023-01-18 18:06:00+00:00,-0.80,4.327507,4h 20m after,1909,4.306242,100.000000,44331
31,CatlinsLake,2024-01-28,2024,2024-01-28 22:25:41.024000+00:00,2.642548,2024-01-28 23:17:00+00:00,-0.76,-0.855271,0h 51m before,1882,4.245336,100.000000,44331
44,CatlinsLake,2025-10-22,2025,2025-10-22 22:37:21.025000+00:00,6.125554,2025-10-22 21:37:00+00:00,-0.74,1.005840,1h 00m after,1782,4.019760,100.000000,44331
17,CatlinsLake,2023-02-10,2023,2023-02-10 22:37:09.024000+00:00,1.910307,2023-02-11 00:28:00+00:00,-0.66,-1.847493,1h 51m before,1654,3.731023,100.000000,44331
16,CatlinsLake,2023-01-28,2023,2023-01-28 22:25:39.024000+00:00,7.650573,2023-01-29 03:13:00+00:00,-0.75,-4.789160,4h 47m before,1475,3.327243,100.000000,44331
37,CatlinsLake,2024-10-24,2024,2024-10-24 22:25:41.024000+00:00,3.620841,2024-10-25 03:44:00+00:00,-0.70,-5.305271,5h 18m before,1433,3.232501,100.000000,44331
10,CatlinsLake,2022-10-30,2022,2022-10-30 22:25:39.024000+00:00,8.228348,2022-10-31 01:33:00+00:00,-0.79,-3.122493,3h 07m before,1272,2.869324,100.000000,44331
1,CatlinsLake,2022-03-19,2022,2022-03-19 22:25:51.024000+00:00,9.322820,2022-03-19 22:02:00+00:00,-0.94,0.397507,0h 24m after,284,0.640635,100.000000,44331

CatlinsRiverMouth: search 2022-2025
  Distinct cloud-filtered dates: 66
  Saved 66 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsRiverMouth\CatlinsRiverMouth_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsRiverMouth\CatlinsRiverMouth_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsRiverMouth\CatlinsRiverMouth_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsRiverMouth\CatlinsRiverMouth_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
31,CatlinsRiverMouth,2023-06-15,2023,2023-06-15 22:37:11.024000+00:00,9.683786,2023-06-15 19:04:00+00:00,-0.85,3.553062,3h 33m after,2069,33.093410,100.0,6252
55,CatlinsRiverMouth,2025-04-10,2025,2025-04-10 22:37:09.024000+00:00,0.002813,2025-04-10 19:41:00+00:00,-0.82,2.935840,2h 56m after,2016,32.245681,100.0,6252
63,CatlinsRiverMouth,2025-09-07,2025,2025-09-07 22:37:09.024000+00:00,2.634845,2025-09-07 20:36:00+00:00,-1.00,2.019173,2h 01m after,1865,29.830454,100.0,6252
62,CatlinsRiverMouth,2025-08-25,2025,2025-08-25 22:25:49.024000+00:00,6.799818,2025-08-25 22:35:00+00:00,-0.83,-0.153049,0h 09m before,1859,29.734485,100.0,6252
64,CatlinsRiverMouth,2025-10-09,2025,2025-10-09 22:26:01.025000+00:00,0.998645,2025-10-09 22:50:00+00:00,-1.01,-0.399715,0h 24m before,1821,29.126679,100.0,6252
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,CatlinsRiverMouth,2022-05-01,2022,2022-05-01 22:37:11.024000+00:00,8.831602,2022-05-01 21:37:00+00:00,-0.84,1.003062,1h 00m after,740,11.836212,100.0,6252
39,CatlinsRiverMouth,2023-11-09,2023,2023-11-09 22:25:41.024000+00:00,8.020958,2023-11-09 18:19:00+00:00,-0.65,4.111396,4h 07m after,202,3.230966,100.0,6252
42,CatlinsRiverMouth,2024-01-26,2024,2024-01-26 22:37:09.024000+00:00,2.877543,2024-01-26 21:59:00+00:00,-0.80,0.635840,0h 38m after,16,0.255918,100.0,6252
2,CatlinsRiverMouth,2022-03-19,2022,2022-03-19 22:25:51.024000+00:00,4.613432,2022-03-19 22:05:00+00:00,-0.93,0.347507,0h 21m after,0,0.000000,100.0,6252
58,CatlinsRiverMouth,2025-06-14,2025,2025-06-14 22:37:31.025000+00:00,7.171769,2025-06-14 23:22:00+00:00,-0.69,-0.741382,0h 44m before,0,0.000000,100.0,6252

Childrens: search 2022-2025
  Distinct cloud-filtered dates: 89
  Saved 89 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Childrens\Childrens_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Childrens\Childrens_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Childrens\Childrens_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Childrens\Childrens_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
30,Childrens,2023-08-31,2023,2023-08-31 22:25:51.024000+00:00,4.747944,2023-08-31 22:20:00+00:00,-1.17,0.097507,0h 06m after,1570,63.640049,100.0,2467
70,Childrens,2025-04-12,2025,2025-04-12 22:26:01.025000+00:00,6.475198,2025-04-12 22:03:00+00:00,-0.83,0.383618,0h 23m after,709,28.739360,100.0,2467
68,Childrens,2025-03-28,2025,2025-03-28 22:25:49.024000+00:00,2.891882,2025-03-28 21:24:00+00:00,-1.12,1.030284,1h 02m after,701,28.415079,100.0,2467
81,Childrens,2025-09-21,2025,2025-09-21 22:15:59.024000+00:00,0.000432,2025-09-21 21:49:00+00:00,-0.85,0.449729,0h 27m after,661,26.793677,100.0,2467
55,Childrens,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,0.002717,2024-08-20 22:34:00+00:00,-1.11,-0.139160,0h 08m before,645,26.145116,100.0,2467
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,Childrens,2023-06-02,2023,2023-06-02 22:25:51.024000+00:00,3.406797,2023-06-02 20:42:00+00:00,-0.88,1.730840,1h 44m after,15,0.608026,100.0,2467
58,Childrens,2024-11-10,2024,2024-11-10 22:16:01.024000+00:00,4.689303,2024-11-10 16:57:00+00:00,-0.80,5.316951,5h 19m after,14,0.567491,100.0,2467
49,Childrens,2024-05-09,2024,2024-05-09 22:15:59.024000+00:00,5.889338,2024-05-09 23:18:00+00:00,-1.01,-1.033604,1h 02m before,0,0.000000,100.0,2467
53,Childrens,2024-07-08,2024,2024-07-08 22:16:09.024000+00:00,4.169291,2024-07-09 00:08:00+00:00,-0.79,-1.864160,1h 52m before,0,0.000000,100.0,2467
61,Childrens,2024-12-08,2024,2024-12-08 22:25:49.024000+00:00,0.410486,2024-12-09 04:16:00+00:00,-0.90,-5.836382,5h 50m before,0,0.000000,100.0,2467

Duvauchelle: search 2022-2025
  Distinct cloud-filtered dates: 89
  Saved 89 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Duvauchelle\Duvauchelle_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Duvauchelle\Duvauchelle_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Duvauchelle\Duvauchelle_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Duvauchelle\Duvauchelle_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
30,Duvauchelle,2023-08-31,2023,2023-08-31 22:25:51.024000+00:00,4.747944,2023-08-31 22:20:00+00:00,-1.18,0.097507,0h 06m after,3889,52.525662,100.000000,7404
68,Duvauchelle,2025-03-28,2025,2025-03-28 22:25:49.024000+00:00,2.891882,2025-03-28 21:24:00+00:00,-1.13,1.030284,1h 02m after,2229,30.105348,100.000000,7404
70,Duvauchelle,2025-04-12,2025,2025-04-12 22:26:01.025000+00:00,6.475198,2025-04-12 22:03:00+00:00,-0.83,0.383618,0h 23m after,1857,25.081037,100.000000,7404
45,Duvauchelle,2024-04-22,2024,2024-04-22 22:25:39.024000+00:00,9.466001,2024-04-22 21:24:00+00:00,-0.79,1.027507,1h 02m after,1844,24.905457,99.783901,7404
48,Duvauchelle,2024-05-07,2024,2024-05-07 22:25:41.024000+00:00,7.194091,2024-05-07 21:34:00+00:00,-1.11,0.861396,0h 52m after,1823,24.621826,100.000000,7404
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Duvauchelle,2025-11-10,2025,2025-11-10 22:15:59.024000+00:00,9.393936,2025-11-11 02:51:00+00:00,-0.96,-4.583604,4h 35m before,249,3.363047,100.000000,7404
88,Duvauchelle,2025-12-23,2025,2025-12-23 22:25:39.024000+00:00,0.585297,2025-12-24 00:58:00+00:00,-0.75,-2.539160,2h 32m before,185,2.498649,100.000000,7404
36,Duvauchelle,2023-12-06,2023,2023-12-06 22:16:01.024000+00:00,6.618736,2023-12-06 17:10:00+00:00,-0.56,5.100284,5h 06m after,175,2.363587,100.000000,7404
35,Duvauchelle,2023-10-22,2023,2023-10-22 22:16:09.024000+00:00,5.264000,2023-10-22 16:05:00+00:00,-0.77,6.185840,6h 11m after,57,0.769854,100.000000,7404
53,Duvauchelle,2024-07-08,2024,2024-07-08 22:16:09.024000+00:00,4.169291,2024-07-09 00:08:00+00:00,-0.79,-1.864160,1h 52m before,0,0.000000,100.000000,7404

Ihutai: search 2022-2025
  Distinct cloud-filtered dates: 38
  Saved 38 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Ihutai\Ihutai_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Ihutai\Ihutai_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Ihutai\Ihutai_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Ihutai\Ihutai_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
13,Ihutai,2023-08-31,2023,2023-08-31 22:25:51.024000+00:00,4.747944,2023-08-31 23:00:00+00:00,-1.18,-0.569160,0h 34m before,47767,56.100769,100.000000,85145
26,Ihutai,2024-09-29,2024,2024-09-29 22:25:49.024000+00:00,2.197607,2024-09-29 20:28:00+00:00,-0.74,1.963618,1h 58m after,22909,26.905866,100.000000,85145
30,Ihutai,2025-04-12,2025,2025-04-12 22:26:01.025000+00:00,6.475198,2025-04-12 22:48:00+00:00,-0.83,-0.366382,0h 22m before,22220,26.096659,100.000000,85145
1,Ihutai,2022-04-13,2022,2022-04-13 22:25:39.024000+00:00,0.151867,2022-04-13 20:30:00+00:00,-0.80,1.927507,1h 56m after,21716,25.504727,100.000000,85145
2,Ihutai,2022-04-28,2022,2022-04-28 22:25:51.024000+00:00,2.347852,2022-04-28 21:20:00+00:00,-0.94,1.097507,1h 06m after,21653,25.430736,100.000000,85145
18,Ihutai,2024-04-22,2024,2024-04-22 22:25:39.024000+00:00,9.466001,2024-04-22 22:09:00+00:00,-0.79,0.277507,0h 17m after,19970,23.454108,100.000000,85145
14,Ihutai,2023-10-10,2023,2023-10-10 22:25:41.024000+00:00,0.203583,2023-10-10 19:47:00+00:00,-0.67,2.644729,2h 39m after,19825,23.283810,100.000000,85145
11,Ihutai,2023-06-02,2023,2023-06-02 22:25:51.024000+00:00,3.406797,2023-06-02 21:24:00+00:00,-0.91,1.030840,1h 02m after,19806,23.261495,100.000000,85145
12,Ihutai,2023-07-17,2023,2023-07-17 22:25:49.024000+00:00,0.433032,2023-07-17 22:40:00+00:00,-0.81,-0.236382,0h 14m before,19247,22.604968,100.000000,85145
20,Ihutai,2024-05-07,2024,2024-05-07 22:25:41.024000+00:00,7.194091,2024-05-07 22:17:00+00:00,-1.13,0.144729,0h 09m after,18648,21.901462,99.985906,85145
10,Ihutai,2023-04-28,2023,2023-04-28 22:25:49.024000+00:00,2.014209,2023-04-28 17:50:00+00:00,-0.70,4.596951,4h 36m after,18122,21.283693,100.000000,85145
21,Ihutai,2024-06-06,2024,2024-06-06 22:25:51.024000+00:00,0.195281,2024-06-06 22:45:00+00:00,-1.02,-0.319160,0h 19m before,17115,20.101004,100.000000,85145
25,Ihutai,2024-09-04,2024,2024-09-04 22:25:41.024000+00:00,0.000717,2024-09-04 23:52:00+00:00,-0.76,-1.438604,1h 26m before,16766,19.691115,100.000000,85145
24,Ihutai,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,0.002717,2024-08-20 23:15:00+00:00,-1.12,-0.822493,0h 49m before,16719,19.635915,100.000000,85145
23,Ihutai,2024-08-05,2024,2024-08-05 22:25:41.024000+00:00,0.001357,2024-08-05 23:34:00+00:00,-0.83,-1.138604,1h 08m before,16475,19.349345,100.000000,85145
15,Ihutai,2023-10-15,2023,2023-10-15 22:25:49.024000+00:00,2.479853,2023-10-15 23:25:00+00:00,-0.73,-0.986382,0h 59m before,15545,18.257091,100.000000,85145
22,Ihutai,2024-07-06,2024,2024-07-06 22:25:51.024000+00:00,1.712278,2024-07-06 23:12:00+00:00,-0.91,-0.769160,0h 46m before,15458,18.154912,99.581890,85145
3,Ihutai,2022-05-23,2022,2022-05-23 22:25:49.024000+00:00,0.003851,2022-05-23 17:37:00+00:00,-0.97,4.813618,4h 49m after,15228,17.884785,99.948323,85145
8,Ihutai,2023-02-27,2023,2023-02-27 22:25:49.025000+00:00,7.803491,2023-02-27 17:06:00+00:00,-0.71,5.330285,5h 20m after,15157,17.801398,100.000000,85145
4,Ihutai,2022-10-10,2022,2022-10-10 22:25:39.024000+00:00,0.294382,2022-10-10 23:16:00+00:00,-0.96,-0.839160,0h 50m before,15024,17.645193,100.000000,85145
32,Ihutai,2025-09-09,2025,2025-09-09 22:26:01.025000+00:00,4.782247,2025-09-10 00:06:00+00:00,-1.04,-1.666382,1h 40m before,14944,17.551236,100.000000,85145
29,Ihutai,2025-03-28,2025,2025-03-28 22:25:49.024000+00:00,2.891882,2025-03-28 22:07:00+00:00,-1.10,0.313618,0h 19m after,14507,17.037994,100.000000,85145
0,Ihutai,2022-02-17,2022,2022-02-17 22:25:51.024000+00:00,0.027729,2022-02-17 23:55:00+00:00,-0.84,-1.485827,1h 29m before,14293,16.786658,100.000000,85145
27,Ihutai,2024-11-23,2024,2024-11-23 22:25:41.024000+00:00,1.469149,2024-11-23 16:57:00+00:00,-0.69,5.478062,5h 29m after,13641,16.020906,100.000000,85145
19,Ihutai,2024-04-27,2024,2024-04-27 22:25:41.024000+00:00,0.011916,2024-04-28 01:32:00+00:00,-0.74,-3.105271,3h 06m before,13439,15.783663,99.821481,85145
34,Ihutai,2025-09-29,2025,2025-09-29 22:26:01.025000+00:00,6.435211,2025-09-29 16:08:00+00:00,-0.60,6.300285,6h 18m after,12191,14.317928,100.000000,85145
36,Ihutai,2025-10-29,2025,2025-10-29 22:26:01.025000+00:00,2.153105,2025-10-29 16:15:00+00:00,-0.61,6.183618,6h 11m after,12138,14.255681,100.000000,85145
9,Ihutai,2023-03-14,2023,2023-03-14 22:25:41.024000+00:00,7.300752,2023-03-15 04:29:00+00:00,-0.83,-6.055271,6h 03m before,12055,14.158201,100.000000,85145
37,Ihutai,2025-12-23,2025,2025-12-23 22:25:39.024000+00:00,0.585297,2025-12-24 01:45:00+00:00,-0.75,-3.322493,3h 19m before,10952,12.862764,100.000000,85145
33,Ihutai,2025-09-14,2025,2025-09-14 22:25:39.024000+00:00,7.040510,2025-09-14 16:19:00+00:00,-0.94,6.110840,6h 07m after,10873,12.769981,100.000000,85145
5,Ihutai,2022-10-15,2022,2022-10-15 22:25:51.024000+00:00,0.012392,2022-10-16 03:35:00+00:00,-0.70,-5.152493,5h 09m before,10699,12.565623,100.000000,85145
35,Ihutai,2025-10-24,2025,2025-10-24 22:25:39.024000+00:00,0.326880,2025-10-25 01:14:00+00:00,-0.67,-2.805827,2h 48m before,10680,12.543308,100.000000,85145
28,Ihutai,2024-12-08,2024,2024-12-08 22:25:49.024000+00:00,0.410486,2024-12-08 16:15:00+00:00,-0.83,6.180284,6h 11m after,10599,12.448177,100.000000,85145
31,Ihutai,2025-06-01,2025,2025-06-01 22:26:01.025000+00:00,0.079051,2025-06-02 03:41:00+00:00,-0.82,-5.249715,5h 15m before,9520,11.180927,100.000000,85145
16,Ihutai,2023-12-29,2023,2023-12-29 22:25:41.024000+00:00,0.533008,2023-12-30 01:10:00+00:00,-0.83,-2.738604,2h 44m before,8989,10.557285,100.000000,85145
7,Ihutai,2023-01-18,2023,2023-01-18 22:25:39.024000+00:00,4.039409,2023-01-18 19:49:00+00:00,-0.83,2.610840,2h 37m after,8719,10.240179,100.000000,85145
6,Ihutai,2022-10-30,2022,2022-10-30 22:25:39.024000+00:00,0.272179,2022-10-31 03:26:00+00:00,-0.94,-5.005827,5h 00m before,8620,10.123906,100.000000,85145
17,Ihutai,2024-04-07,2024,2024-04-07 22:25:41.024000+00:00,5.908886,2024-04-07 21:50:00+00:00,-1.15,0.594729,0h 36m after,443,0.520289,100.000000,85145

IveyBay_Feb26: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Feb26\IveyBay_Feb26_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Feb26\IveyBay_Feb26_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Feb26\IveyBay_Feb26_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Feb26\IveyBay_Feb26_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
17,IveyBay_Feb26,2023-05-30,2023,2023-05-30 22:16:11.024000+00:00,5.582327,2023-05-31 01:00:00+00:00,-0.32,-2.730271,2h 44m before,152,44.837758,100.0,339
25,IveyBay_Feb26,2023-09-07,2023,2023-09-07 22:16:11.024000+00:00,0.000348,2023-09-07 20:24:00+00:00,-0.22,1.869729,1h 52m after,118,34.808260,100.0,339
20,IveyBay_Feb26,2023-06-12,2023,2023-06-12 22:25:51.024000+00:00,0.632771,2023-06-12 23:38:00+00:00,-0.28,-1.202493,1h 12m before,90,26.548673,100.0,339
64,IveyBay_Feb26,2025-07-18,2025,2025-07-18 22:16:31.024000+00:00,3.950156,2025-07-18 21:32:00+00:00,-0.32,0.741951,0h 45m after,90,26.548673,100.0,339
22,IveyBay_Feb26,2023-07-17,2023,2023-07-17 22:25:49.024000+00:00,0.580988,2023-07-18 04:26:00+00:00,-0.44,-6.003049,6h 00m before,88,25.958702,100.0,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,IveyBay_Feb26,2023-01-13,2023,2023-01-13 22:25:41.024000+00:00,6.727295,2023-01-13 19:45:00+00:00,-0.39,2.678062,2h 41m after,0,0.000000,100.0,339
51,IveyBay_Feb26,2025-01-17,2025,2025-01-17 22:25:39.024000+00:00,8.726227,2025-01-17 18:16:00+00:00,-0.52,4.160840,4h 10m after,0,0.000000,100.0,339
46,IveyBay_Feb26,2024-09-24,2024,2024-09-24 22:25:41.024000+00:00,5.542720,2024-09-24 19:40:00+00:00,-0.27,2.761396,2h 46m after,0,0.000000,100.0,339
43,IveyBay_Feb26,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,3.418219,2024-08-20 16:45:00+00:00,-0.68,5.677507,5h 41m after,0,0.000000,100.0,339
59,IveyBay_Feb26,2025-05-02,2025,2025-05-02 22:26:01.025000+00:00,5.353211,2025-05-02 18:49:00+00:00,-0.41,3.616951,3h 37m after,0,0.000000,100.0,339

IveyBay_Nov25: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Nov25\IveyBay_Nov25_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Nov25\IveyBay_Nov25_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Nov25\IveyBay_Nov25_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Nov25\IveyBay_Nov25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
17,IveyBay_Nov25,2023-05-30,2023,2023-05-30 22:16:11.024000+00:00,5.582327,2023-05-31 01:00:00+00:00,-0.32,-2.730271,2h 44m before,152,44.837758,100.0,339
25,IveyBay_Nov25,2023-09-07,2023,2023-09-07 22:16:11.024000+00:00,0.000348,2023-09-07 20:24:00+00:00,-0.22,1.869729,1h 52m after,118,34.808260,100.0,339
20,IveyBay_Nov25,2023-06-12,2023,2023-06-12 22:25:51.024000+00:00,0.632771,2023-06-12 23:38:00+00:00,-0.28,-1.202493,1h 12m before,90,26.548673,100.0,339
64,IveyBay_Nov25,2025-07-18,2025,2025-07-18 22:16:31.024000+00:00,3.950156,2025-07-18 21:32:00+00:00,-0.32,0.741951,0h 45m after,90,26.548673,100.0,339
22,IveyBay_Nov25,2023-07-17,2023,2023-07-17 22:25:49.024000+00:00,0.580988,2023-07-18 04:26:00+00:00,-0.44,-6.003049,6h 00m before,88,25.958702,100.0,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,IveyBay_Nov25,2023-01-13,2023,2023-01-13 22:25:41.024000+00:00,6.727295,2023-01-13 19:45:00+00:00,-0.39,2.678062,2h 41m after,0,0.000000,100.0,339
51,IveyBay_Nov25,2025-01-17,2025,2025-01-17 22:25:39.024000+00:00,8.726227,2025-01-17 18:16:00+00:00,-0.52,4.160840,4h 10m after,0,0.000000,100.0,339
46,IveyBay_Nov25,2024-09-24,2024,2024-09-24 22:25:41.024000+00:00,5.542720,2024-09-24 19:40:00+00:00,-0.27,2.761396,2h 46m after,0,0.000000,100.0,339
43,IveyBay_Nov25,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,3.418219,2024-08-20 16:45:00+00:00,-0.68,5.677507,5h 41m after,0,0.000000,100.0,339
59,IveyBay_Nov25,2025-05-02,2025,2025-05-02 22:26:01.025000+00:00,5.353211,2025-05-02 18:49:00+00:00,-0.41,3.616951,3h 37m after,0,0.000000,100.0,339

IveyBay_ThePoint_LeftBank_Oct24: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
17,IveyBay_ThePoint_LeftBank_Oct24,2023-05-30,2023,2023-05-30 22:16:11.024000+00:00,5.582327,2023-05-31 01:00:00+00:00,-0.32,-2.730271,2h 44m before,362,23.400129,100.0,1547
25,IveyBay_ThePoint_LeftBank_Oct24,2023-09-07,2023,2023-09-07 22:16:11.024000+00:00,0.000348,2023-09-07 20:24:00+00:00,-0.22,1.869729,1h 52m after,309,19.974144,100.0,1547
72,IveyBay_ThePoint_LeftBank_Oct24,2025-12-23,2025,2025-12-23 22:25:39.024000+00:00,7.287385,2025-12-23 18:02:00+00:00,-0.47,4.394173,4h 24m after,302,19.521655,100.0,1547
20,IveyBay_ThePoint_LeftBank_Oct24,2023-06-12,2023,2023-06-12 22:25:51.024000+00:00,0.632771,2023-06-12 23:38:00+00:00,-0.28,-1.202493,1h 12m before,205,13.251454,100.0,1547
64,IveyBay_ThePoint_LeftBank_Oct24,2025-07-18,2025,2025-07-18 22:16:31.024000+00:00,3.950156,2025-07-18 21:32:00+00:00,-0.32,0.741951,0h 45m after,205,13.251454,100.0,1547
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,IveyBay_ThePoint_LeftBank_Oct24,2023-01-13,2023,2023-01-13 22:25:41.024000+00:00,6.727295,2023-01-13 19:45:00+00:00,-0.39,2.678062,2h 41m after,0,0.000000,100.0,1547
33,IveyBay_ThePoint_LeftBank_Oct24,2024-04-17,2024,2024-04-17 22:25:51.024000+00:00,7.906822,2024-04-18 00:01:00+00:00,-0.11,-1.585827,1h 35m before,0,0.000000,100.0,1547
43,IveyBay_ThePoint_LeftBank_Oct24,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,3.418219,2024-08-20 16:45:00+00:00,-0.68,5.677507,5h 41m after,0,0.000000,100.0,1547
51,IveyBay_ThePoint_LeftBank_Oct24,2025-01-17,2025,2025-01-17 22:25:39.024000+00:00,8.726227,2025-01-17 18:16:00+00:00,-0.52,4.160840,4h 10m after,0,0.000000,100.0,1547
59,IveyBay_ThePoint_LeftBank_Oct24,2025-05-02,2025,2025-05-02 22:26:01.025000+00:00,5.353211,2025-05-02 18:49:00+00:00,-0.41,3.616951,3h 37m after,0,0.000000,100.0,1547

LeftBank_Feb26: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Feb26\LeftBank_Feb26_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Feb26\LeftBank_Feb26_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Feb26\LeftBank_Feb26_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Feb26\LeftBank_Feb26_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
25,LeftBank_Feb26,2023-09-07,2023,2023-09-07 22:16:11.024000+00:00,0.000348,2023-09-07 20:24:00+00:00,-0.22,1.869729,1h 52m after,76,8.735632,100.0,870
64,LeftBank_Feb26,2025-07-18,2025,2025-07-18 22:16:31.024000+00:00,3.950156,2025-07-18 21:32:00+00:00,-0.32,0.741951,0h 45m after,32,3.678161,100.0,870
63,LeftBank_Feb26,2025-06-16,2025,2025-06-16 22:25:39.024000+00:00,7.532189,2025-06-16 19:20:00+00:00,-0.45,3.094173,3h 06m after,28,3.218391,100.0,870
14,LeftBank_Feb26,2023-03-14,2023,2023-03-14 22:25:41.024000+00:00,0.044448,2023-03-14 19:57:00+00:00,-0.35,2.478062,2h 29m after,16,1.839080,100.0,870
30,LeftBank_Feb26,2024-02-04,2024,2024-02-04 22:16:01.024000+00:00,7.283566,2024-02-04 22:19:00+00:00,-0.19,-0.049716,0h 03m before,12,1.379310,100.0,870
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,LeftBank_Feb26,2025-08-22,2025,2025-08-22 22:16:09.024000+00:00,2.638276,2025-08-23 04:10:00+00:00,-0.52,-5.897493,5h 54m before,0,0.000000,100.0,870
68,LeftBank_Feb26,2025-09-09,2025,2025-09-09 22:26:01.025000+00:00,6.096213,2025-09-09 17:11:00+00:00,-0.71,5.250285,5h 15m after,0,0.000000,100.0,870
69,LeftBank_Feb26,2025-09-14,2025,2025-09-14 22:25:39.024000+00:00,1.723290,2025-09-14 20:09:00+00:00,-0.24,2.277507,2h 17m after,0,0.000000,100.0,870
71,LeftBank_Feb26,2025-12-08,2025,2025-12-08 22:25:51.025000+00:00,4.890863,2025-12-08 18:19:00+00:00,-0.46,4.114174,4h 07m after,0,0.000000,100.0,870
72,LeftBank_Feb26,2025-12-23,2025,2025-12-23 22:25:39.024000+00:00,7.287385,2025-12-23 18:02:00+00:00,-0.47,4.394173,4h 24m after,0,0.000000,100.0,870

LeftBank_Nov25: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Nov25\LeftBank_Nov25_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Nov25\LeftBank_Nov25_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Nov25\LeftBank_Nov25_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Nov25\LeftBank_Nov25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
25,LeftBank_Nov25,2023-09-07,2023,2023-09-07 22:16:11.024000+00:00,0.000348,2023-09-07 20:24:00+00:00,-0.22,1.869729,1h 52m after,76,8.725603,100.0,871
64,LeftBank_Nov25,2025-07-18,2025,2025-07-18 22:16:31.024000+00:00,3.950156,2025-07-18 21:32:00+00:00,-0.32,0.741951,0h 45m after,32,3.673938,100.0,871
63,LeftBank_Nov25,2025-06-16,2025,2025-06-16 22:25:39.024000+00:00,7.532189,2025-06-16 19:20:00+00:00,-0.45,3.094173,3h 06m after,28,3.214696,100.0,871
14,LeftBank_Nov25,2023-03-14,2023,2023-03-14 22:25:41.024000+00:00,0.044448,2023-03-14 19:57:00+00:00,-0.35,2.478062,2h 29m after,16,1.836969,100.0,871
30,LeftBank_Nov25,2024-02-04,2024,2024-02-04 22:16:01.024000+00:00,7.283566,2024-02-04 22:19:00+00:00,-0.19,-0.049716,0h 03m before,12,1.377727,100.0,871
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,LeftBank_Nov25,2025-08-22,2025,2025-08-22 22:16:09.024000+00:00,2.638276,2025-08-23 04:10:00+00:00,-0.52,-5.897493,5h 54m before,0,0.000000,100.0,871
68,LeftBank_Nov25,2025-09-09,2025,2025-09-09 22:26:01.025000+00:00,6.096213,2025-09-09 17:11:00+00:00,-0.71,5.250285,5h 15m after,0,0.000000,100.0,871
69,LeftBank_Nov25,2025-09-14,2025,2025-09-14 22:25:39.024000+00:00,1.723290,2025-09-14 20:09:00+00:00,-0.24,2.277507,2h 17m after,0,0.000000,100.0,871
71,LeftBank_Nov25,2025-12-08,2025,2025-12-08 22:25:51.025000+00:00,4.890863,2025-12-08 18:19:00+00:00,-0.46,4.114174,4h 07m after,0,0.000000,100.0,871
72,LeftBank_Nov25,2025-12-23,2025,2025-12-23 22:25:39.024000+00:00,7.287385,2025-12-23 18:02:00+00:00,-0.47,4.394173,4h 24m after,0,0.000000,100.0,871

Paremata_Feb25: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb25\Paremata_Feb25_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb25\Paremata_Feb25_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb25\Paremata_Feb25_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb25\Paremata_Feb25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
34,Paremata_Feb25,2024-04-22,2024,2024-04-22 22:25:39.024000+00:00,6.756297,2024-04-23 03:44:00+00:00,-0.54,-5.305827,5h 18m before,461,34.924242,100.0,1320
25,Paremata_Feb25,2023-09-07,2023,2023-09-07 22:16:11.024000+00:00,0.000348,2023-09-07 20:23:00+00:00,-0.22,1.886396,1h 53m after,457,34.621212,100.0,1320
11,Paremata_Feb25,2023-01-15,2023,2023-01-15 22:15:59.024000+00:00,1.347796,2023-01-15 21:24:00+00:00,-0.28,0.866396,0h 52m after,453,34.318182,100.0,1320
52,Paremata_Feb25,2025-02-06,2025,2025-02-06 22:25:49.024000+00:00,9.279174,2025-02-06 21:33:00+00:00,-0.21,0.880284,0h 53m after,453,34.318182,100.0,1320
64,Paremata_Feb25,2025-07-18,2025,2025-07-18 22:16:31.024000+00:00,3.950156,2025-07-18 21:32:00+00:00,-0.32,0.741951,0h 45m after,449,34.015152,100.0,1320
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,Paremata_Feb25,2023-02-07,2023,2023-02-07 22:25:39.024000+00:00,2.965261,2023-02-07 17:23:00+00:00,-0.54,5.044173,5h 03m after,2,0.151515,100.0,1320
2,Paremata_Feb25,2022-04-25,2022,2022-04-25 22:16:11.024000+00:00,4.320996,2022-04-26 00:56:00+00:00,-0.22,-2.663604,2h 40m before,0,0.000000,100.0,1320
33,Paremata_Feb25,2024-04-17,2024,2024-04-17 22:25:51.024000+00:00,7.906822,2024-04-18 00:03:00+00:00,-0.11,-1.619160,1h 37m before,0,0.000000,100.0,1320
43,Paremata_Feb25,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,3.418219,2024-08-20 16:46:00+00:00,-0.68,5.660840,5h 40m after,0,0.000000,100.0,1320
46,Paremata_Feb25,2024-09-24,2024,2024-09-24 22:25:41.024000+00:00,5.542720,2024-09-24 19:40:00+00:00,-0.27,2.761396,2h 46m after,0,0.000000,100.0,1320

Paremata_Feb26: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb26\Paremata_Feb26_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb26\Paremata_Feb26_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb26\Paremata_Feb26_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb26\Paremata_Feb26_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
34,Paremata_Feb26,2024-04-22,2024,2024-04-22 22:25:39.024000+00:00,6.756297,2024-04-23 03:44:00+00:00,-0.54,-5.305827,5h 18m before,461,33.576111,100.0,1373
25,Paremata_Feb26,2023-09-07,2023,2023-09-07 22:16:11.024000+00:00,0.000348,2023-09-07 20:23:00+00:00,-0.22,1.886396,1h 53m after,457,33.284778,100.0,1373
11,Paremata_Feb26,2023-01-15,2023,2023-01-15 22:15:59.024000+00:00,1.347796,2023-01-15 21:24:00+00:00,-0.28,0.866396,0h 52m after,453,32.993445,100.0,1373
52,Paremata_Feb26,2025-02-06,2025,2025-02-06 22:25:49.024000+00:00,9.279174,2025-02-06 21:33:00+00:00,-0.21,0.880284,0h 53m after,453,32.993445,100.0,1373
64,Paremata_Feb26,2025-07-18,2025,2025-07-18 22:16:31.024000+00:00,3.950156,2025-07-18 21:32:00+00:00,-0.32,0.741951,0h 45m after,449,32.702112,100.0,1373
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,Paremata_Feb26,2023-02-07,2023,2023-02-07 22:25:39.024000+00:00,2.965261,2023-02-07 17:23:00+00:00,-0.54,5.044173,5h 03m after,6,0.436999,100.0,1373
2,Paremata_Feb26,2022-04-25,2022,2022-04-25 22:16:11.024000+00:00,4.320996,2022-04-26 00:56:00+00:00,-0.22,-2.663604,2h 40m before,0,0.000000,100.0,1373
33,Paremata_Feb26,2024-04-17,2024,2024-04-17 22:25:51.024000+00:00,7.906822,2024-04-18 00:03:00+00:00,-0.11,-1.619160,1h 37m before,0,0.000000,100.0,1373
43,Paremata_Feb26,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,3.418219,2024-08-20 16:46:00+00:00,-0.68,5.660840,5h 40m after,0,0.000000,100.0,1373
46,Paremata_Feb26,2024-09-24,2024,2024-09-24 22:25:41.024000+00:00,5.542720,2024-09-24 19:40:00+00:00,-0.27,2.761396,2h 46m after,0,0.000000,100.0,1373

Paremata_Nov25: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Nov25\Paremata_Nov25_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Nov25\Paremata_Nov25_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Nov25\Paremata_Nov25_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Nov25\Paremata_Nov25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
17,Paremata_Nov25,2023-05-30,2023,2023-05-30 22:16:11.024000+00:00,5.582327,2023-05-31 01:00:00+00:00,-0.32,-2.730271,2h 44m before,487,19.740576,100.0,2467
34,Paremata_Nov25,2024-04-22,2024,2024-04-22 22:25:39.024000+00:00,6.756297,2024-04-23 03:44:00+00:00,-0.54,-5.305827,5h 18m before,481,19.497365,100.0,2467
25,Paremata_Nov25,2023-09-07,2023,2023-09-07 22:16:11.024000+00:00,0.000348,2023-09-07 20:23:00+00:00,-0.22,1.886396,1h 53m after,477,19.335225,100.0,2467
11,Paremata_Nov25,2023-01-15,2023,2023-01-15 22:15:59.024000+00:00,1.347796,2023-01-15 21:24:00+00:00,-0.28,0.866396,0h 52m after,473,19.173085,100.0,2467
52,Paremata_Nov25,2025-02-06,2025,2025-02-06 22:25:49.024000+00:00,9.279174,2025-02-06 21:33:00+00:00,-0.21,0.880284,0h 53m after,473,19.173085,100.0,2467
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,Paremata_Nov25,2022-11-04,2022,2022-11-04 22:25:51.024000+00:00,5.807608,2022-11-05 01:56:00+00:00,-0.36,-3.502493,3h 30m before,14,0.567491,100.0,2467
2,Paremata_Nov25,2022-04-25,2022,2022-04-25 22:16:11.024000+00:00,4.320996,2022-04-26 00:56:00+00:00,-0.22,-2.663604,2h 40m before,11,0.445886,100.0,2467
46,Paremata_Nov25,2024-09-24,2024,2024-09-24 22:25:41.024000+00:00,5.542720,2024-09-24 19:40:00+00:00,-0.27,2.761396,2h 46m after,2,0.081070,100.0,2467
33,Paremata_Nov25,2024-04-17,2024,2024-04-17 22:25:51.024000+00:00,7.906822,2024-04-18 00:03:00+00:00,-0.11,-1.619160,1h 37m before,0,0.000000,100.0,2467
43,Paremata_Nov25,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,3.418219,2024-08-20 16:46:00+00:00,-0.68,5.660840,5h 40m after,0,0.000000,100.0,2467

Purau: search 2022-2025
  Distinct cloud-filtered dates: 38
  Saved 38 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Purau\Purau_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Purau\Purau_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Purau\Purau_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Purau\Purau_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
13,Purau,2023-08-31,2023,2023-08-31 22:25:51.024000+00:00,4.747944,2023-08-31 23:00:00+00:00,-1.21,-0.569160,0h 34m before,1623,45.449454,100.000000,3571
26,Purau,2024-09-29,2024,2024-09-29 22:25:49.024000+00:00,2.197607,2024-09-29 20:28:00+00:00,-0.76,1.963618,1h 58m after,893,25.007001,100.000000,3571
20,Purau,2024-05-07,2024,2024-05-07 22:25:41.024000+00:00,7.194091,2024-05-07 22:16:00+00:00,-1.15,0.161396,0h 10m after,858,24.026883,100.000000,3571
2,Purau,2022-04-28,2022,2022-04-28 22:25:51.024000+00:00,2.347852,2022-04-28 21:19:00+00:00,-0.96,1.114173,1h 07m after,856,23.970877,100.000000,3571
24,Purau,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,0.002717,2024-08-20 23:15:00+00:00,-1.15,-0.822493,0h 49m before,840,23.522823,100.000000,3571
17,Purau,2024-04-07,2024,2024-04-07 22:25:41.024000+00:00,5.908886,2024-04-07 21:49:00+00:00,-1.18,0.611396,0h 37m after,839,23.494819,100.000000,3571
30,Purau,2025-04-12,2025,2025-04-12 22:26:01.025000+00:00,6.475198,2025-04-12 22:48:00+00:00,-0.85,-0.366382,0h 22m before,837,23.438813,100.000000,3571
18,Purau,2024-04-22,2024,2024-04-22 22:25:39.024000+00:00,9.466001,2024-04-22 22:08:00+00:00,-0.81,0.294173,0h 18m after,814,22.794735,100.000000,3571
32,Purau,2025-09-09,2025,2025-09-09 22:26:01.025000+00:00,4.782247,2025-09-10 00:06:00+00:00,-1.07,-1.666382,1h 40m before,808,22.626715,100.000000,3571
25,Purau,2024-09-04,2024,2024-09-04 22:25:41.024000+00:00,0.000717,2024-09-04 23:51:00+00:00,-0.78,-1.421938,1h 25m before,779,21.814618,100.000000,3571
21,Purau,2024-06-06,2024,2024-06-06 22:25:51.024000+00:00,0.195281,2024-06-06 22:44:00+00:00,-1.04,-0.302493,0h 18m before,762,21.338561,100.000000,3571
4,Purau,2022-10-10,2022,2022-10-10 22:25:39.024000+00:00,0.294382,2022-10-10 23:15:00+00:00,-0.98,-0.822493,0h 49m before,754,21.114534,100.000000,3571
1,Purau,2022-04-13,2022,2022-04-13 22:25:39.024000+00:00,0.151867,2022-04-13 20:30:00+00:00,-0.82,1.927507,1h 56m after,745,20.862504,100.000000,3571
12,Purau,2023-07-17,2023,2023-07-17 22:25:49.024000+00:00,0.433032,2023-07-17 22:40:00+00:00,-0.83,-0.236382,0h 14m before,740,20.722487,100.000000,3571
23,Purau,2024-08-05,2024,2024-08-05 22:25:41.024000+00:00,0.001357,2024-08-05 23:34:00+00:00,-0.85,-1.138604,1h 08m before,731,20.470456,100.000000,3571
15,Purau,2023-10-15,2023,2023-10-15 22:25:49.024000+00:00,2.479853,2023-10-15 23:25:00+00:00,-0.75,-0.986382,0h 59m before,727,20.358443,100.000000,3571
29,Purau,2025-03-28,2025,2025-03-28 22:25:49.024000+00:00,2.891882,2025-03-28 22:06:00+00:00,-1.13,0.330284,0h 20m after,717,20.078409,100.000000,3571
11,Purau,2023-06-02,2023,2023-06-02 22:25:51.024000+00:00,3.406797,2023-06-02 21:23:00+00:00,-0.93,1.047507,1h 03m after,700,19.602352,100.000000,3571
34,Purau,2025-09-29,2025,2025-09-29 22:26:01.025000+00:00,6.435211,2025-09-29 16:07:00+00:00,-0.62,6.316951,6h 19m after,694,19.434332,100.000000,3571
33,Purau,2025-09-14,2025,2025-09-14 22:25:39.024000+00:00,7.040510,2025-09-14 16:18:00+00:00,-0.96,6.127507,6h 08m after,661,18.510221,100.000000,3571
0,Purau,2022-02-17,2022,2022-02-17 22:25:51.024000+00:00,0.027729,2022-02-17 23:55:00+00:00,-0.86,-1.485827,1h 29m before,639,17.894147,100.000000,3571
19,Purau,2024-04-27,2024,2024-04-27 22:25:41.024000+00:00,0.011916,2024-04-28 01:31:00+00:00,-0.76,-3.088604,3h 05m before,638,17.866144,100.000000,3571
10,Purau,2023-04-28,2023,2023-04-28 22:25:49.024000+00:00,2.014209,2023-04-28 17:49:00+00:00,-0.71,4.613618,4h 37m after,631,17.670120,100.000000,3571
22,Purau,2024-07-06,2024,2024-07-06 22:25:51.024000+00:00,1.712278,2024-07-06 23:11:00+00:00,-0.93,-0.752493,0h 45m before,628,17.586110,100.000000,3571
14,Purau,2023-10-10,2023,2023-10-10 22:25:41.024000+00:00,0.203583,2023-10-10 19:47:00+00:00,-0.69,2.644729,2h 39m after,611,17.110053,100.000000,3571
9,Purau,2023-03-14,2023,2023-03-14 22:25:41.024000+00:00,7.300752,2023-03-15 04:29:00+00:00,-0.85,-6.055271,6h 03m before,591,16.549986,100.000000,3571
27,Purau,2024-11-23,2024,2024-11-23 22:25:41.024000+00:00,1.469149,2024-11-23 16:56:00+00:00,-0.71,5.494729,5h 30m after,575,16.101932,100.000000,3571
35,Purau,2025-10-24,2025,2025-10-24 22:25:39.024000+00:00,0.326880,2025-10-25 01:12:00+00:00,-0.69,-2.772493,2h 46m before,569,15.933912,100.000000,3571
7,Purau,2023-01-18,2023,2023-01-18 22:25:39.024000+00:00,4.039409,2023-01-18 19:49:00+00:00,-0.85,2.610840,2h 37m after,556,15.569868,100.000000,3571
3,Purau,2022-05-23,2022,2022-05-23 22:25:49.024000+00:00,0.003851,2022-05-23 17:36:00+00:00,-0.99,4.830284,4h 50m after,545,15.261831,99.887987,3571
16,Purau,2023-12-29,2023,2023-12-29 22:25:41.024000+00:00,0.533008,2023-12-30 01:09:00+00:00,-0.85,-2.721938,2h 43m before,538,15.065808,100.000000,3571
36,Purau,2025-10-29,2025,2025-10-29 22:26:01.025000+00:00,2.153105,2025-10-29 16:15:00+00:00,-0.63,6.183618,6h 11m after,529,14.813778,100.000000,3571
5,Purau,2022-10-15,2022,2022-10-15 22:25:51.024000+00:00,0.012392,2022-10-16 03:34:00+00:00,-0.71,-5.135827,5h 08m before,508,14.225707,100.000000,3571
31,Purau,2025-06-01,2025,2025-06-01 22:26:01.025000+00:00,0.079051,2025-06-02 03:40:00+00:00,-0.84,-5.233049,5h 14m before,487,13.637637,100.000000,3571
37,Purau,2025-12-23,2025,2025-12-23 22:25:39.024000+00:00,0.585297,2025-12-24 01:44:00+00:00,-0.77,-3.305827,3h 18m before,482,13.497620,100.000000,3571
6,Purau,2022-10-30,2022,2022-10-30 22:25:39.024000+00:00,0.272179,2022-10-31 03:25:00+00:00,-0.96,-4.989160,4h 59m before,471,13.189583,100.000000,3571
28,Purau,2024-12-08,2024,2024-12-08 22:25:49.024000+00:00,0.410486,2024-12-08 16:14:00+00:00,-0.84,6.196951,6h 12m after,466,13.049566,100.000000,3571
8,Purau,2023-02-27,2023,2023-02-27 22:25:49.025000+00:00,7.803491,2023-02-27 17:05:00+00:00,-0.73,5.346951,5h 21m after,407,11.397368,100.000000,3571

Robinsons: search 2022-2025
  Distinct cloud-filtered dates: 89
  Saved 89 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Robinsons\Robinsons_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Robinsons\Robinsons_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Robinsons\Robinsons_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Robinsons\Robinsons_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
30,Robinsons,2023-08-31,2023,2023-08-31 22:25:51.024000+00:00,4.747944,2023-08-31 22:20:00+00:00,-1.18,0.097507,0h 06m after,3068,73.714560,100.0,4162
48,Robinsons,2024-05-07,2024,2024-05-07 22:25:41.024000+00:00,7.194091,2024-05-07 21:34:00+00:00,-1.11,0.861396,0h 52m after,1469,35.295531,100.0,4162
68,Robinsons,2025-03-28,2025,2025-03-28 22:25:49.024000+00:00,2.891882,2025-03-28 21:24:00+00:00,-1.13,1.030284,1h 02m after,1441,34.622778,100.0,4162
70,Robinsons,2025-04-12,2025,2025-04-12 22:26:01.025000+00:00,6.475198,2025-04-12 22:03:00+00:00,-0.83,0.383618,0h 23m after,1405,33.757809,100.0,4162
81,Robinsons,2025-09-21,2025,2025-09-21 22:15:59.024000+00:00,0.000432,2025-09-21 21:49:00+00:00,-0.86,0.449729,0h 27m after,1297,31.162902,100.0,4162
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Robinsons,2025-11-10,2025,2025-11-10 22:15:59.024000+00:00,9.393936,2025-11-11 02:51:00+00:00,-0.96,-4.583604,4h 35m before,121,2.907256,100.0,4162
41,Robinsons,2024-02-19,2024,2024-02-19 22:15:59.024000+00:00,4.837792,2024-02-19 18:58:00+00:00,-0.75,3.299729,3h 18m after,22,0.528592,100.0,4162
0,Robinsons,2022-01-15,2022,2022-01-15 22:16:01.024000+00:00,8.863769,2022-01-15 20:57:00+00:00,-0.71,1.316951,1h 19m after,14,0.336377,100.0,4162
53,Robinsons,2024-07-08,2024,2024-07-08 22:16:09.024000+00:00,4.169291,2024-07-09 00:08:00+00:00,-0.79,-1.864160,1h 52m before,0,0.000000,100.0,4162
43,Robinsons,2024-03-20,2024,2024-03-20 22:15:59.024000+00:00,7.258695,2024-03-20 19:21:00+00:00,-0.77,2.916396,2h 55m after,0,0.000000,100.0,4162

Takamatua: search 2022-2025
  Distinct cloud-filtered dates: 89
  Saved 89 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takamatua\Takamatua_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takamatua\Takamatua_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takamatua\Takamatua_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takamatua\Takamatua_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
30,Takamatua,2023-08-31,2023,2023-08-31 22:25:51.024000+00:00,4.747944,2023-08-31 22:20:00+00:00,-1.18,0.097507,0h 06m after,4790,72.652814,100.0,6593
81,Takamatua,2025-09-21,2025,2025-09-21 22:15:59.024000+00:00,0.000432,2025-09-21 21:49:00+00:00,-0.86,0.449729,0h 27m after,1677,25.436069,100.0,6593
56,Takamatua,2024-09-04,2024,2024-09-04 22:25:41.024000+00:00,0.000717,2024-09-04 23:09:00+00:00,-0.76,-0.721938,0h 43m before,1617,24.526012,100.0,6593
79,Takamatua,2025-09-09,2025,2025-09-09 22:26:01.025000+00:00,4.782247,2025-09-09 23:23:00+00:00,-1.04,-0.949715,0h 57m before,1605,24.344001,100.0,6593
68,Takamatua,2025-03-28,2025,2025-03-28 22:25:49.024000+00:00,2.891882,2025-03-28 21:24:00+00:00,-1.13,1.030284,1h 02m after,1601,24.283331,100.0,6593
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,Takamatua,2023-02-27,2023,2023-02-27 22:25:49.025000+00:00,7.803491,2023-02-27 16:29:00+00:00,-0.69,5.946951,5h 57m after,53,0.803883,100.0,6593
43,Takamatua,2024-03-20,2024,2024-03-20 22:15:59.024000+00:00,7.258695,2024-03-20 19:21:00+00:00,-0.77,2.916396,2h 55m after,31,0.470196,100.0,6593
58,Takamatua,2024-11-10,2024,2024-11-10 22:16:01.024000+00:00,4.689303,2024-11-10 16:57:00+00:00,-0.80,5.316951,5h 19m after,16,0.242682,100.0,6593
41,Takamatua,2024-02-19,2024,2024-02-19 22:15:59.024000+00:00,4.837792,2024-02-19 18:58:00+00:00,-0.75,3.299729,3h 18m after,10,0.151676,100.0,6593
53,Takamatua,2024-07-08,2024,2024-07-08 22:16:09.024000+00:00,4.169291,2024-07-09 00:08:00+00:00,-0.79,-1.864160,1h 52m before,0,0.000000,100.0,6593

Takapuwahia_Feb26: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Feb26\Takapuwahia_Feb26_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Feb26\Takapuwahia_Feb26_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Feb26\Takapuwahia_Feb26_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Feb26\Takapuwahia_Feb26_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
72,Takapuwahia_Feb26,2025-12-23,2025,2025-12-23 22:25:39.024000+00:00,7.287385,2025-12-23 18:03:00+00:00,-0.46,4.377507,4h 23m after,63,54.782609,100.0,115
11,Takapuwahia_Feb26,2023-01-15,2023,2023-01-15 22:15:59.024000+00:00,1.347796,2023-01-15 21:24:00+00:00,-0.28,0.866396,0h 52m after,62,53.913043,100.0,115
50,Takapuwahia_Feb26,2024-11-23,2024,2024-11-23 22:25:41.024000+00:00,2.004982,2024-11-23 21:32:00+00:00,-0.16,0.894729,0h 54m after,62,53.913043,100.0,115
8,Takapuwahia_Feb26,2022-12-04,2022,2022-12-04 22:25:51.024000+00:00,9.814896,2022-12-05 01:56:00+00:00,-0.36,-3.502493,3h 30m before,62,53.913043,100.0,115
71,Takapuwahia_Feb26,2025-12-08,2025,2025-12-08 22:25:51.025000+00:00,4.890863,2025-12-08 18:20:00+00:00,-0.46,4.097507,4h 06m after,55,47.826087,100.0,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,Takapuwahia_Feb26,2023-08-28,2023,2023-08-28 22:16:11.024000+00:00,4.629065,2023-08-29 02:59:00+00:00,-0.41,-4.713604,4h 43m before,0,0.000000,100.0,115
51,Takapuwahia_Feb26,2025-01-17,2025,2025-01-17 22:25:39.024000+00:00,8.726227,2025-01-17 18:17:00+00:00,-0.51,4.144173,4h 09m after,0,0.000000,100.0,115
46,Takapuwahia_Feb26,2024-09-24,2024,2024-09-24 22:25:41.024000+00:00,5.542720,2024-09-24 19:40:00+00:00,-0.27,2.761396,2h 46m after,0,0.000000,100.0,115
43,Takapuwahia_Feb26,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,3.418219,2024-08-20 16:47:00+00:00,-0.67,5.644173,5h 39m after,0,0.000000,100.0,115
59,Takapuwahia_Feb26,2025-05-02,2025,2025-05-02 22:26:01.025000+00:00,5.353211,2025-05-02 18:50:00+00:00,-0.40,3.600285,3h 36m after,0,0.000000,100.0,115

Takapuwahia_Nov25: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Nov25\Takapuwahia_Nov25_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Nov25\Takapuwahia_Nov25_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Nov25\Takapuwahia_Nov25_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Nov25\Takapuwahia_Nov25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
72,Takapuwahia_Nov25,2025-12-23,2025,2025-12-23 22:25:39.024000+00:00,7.287385,2025-12-23 18:03:00+00:00,-0.46,4.377507,4h 23m after,77,56.204380,100.0,137
50,Takapuwahia_Nov25,2024-11-23,2024,2024-11-23 22:25:41.024000+00:00,2.004982,2024-11-23 21:32:00+00:00,-0.16,0.894729,0h 54m after,73,53.284672,100.0,137
8,Takapuwahia_Nov25,2022-12-04,2022,2022-12-04 22:25:51.024000+00:00,9.814896,2022-12-05 01:56:00+00:00,-0.36,-3.502493,3h 30m before,73,53.284672,100.0,137
11,Takapuwahia_Nov25,2023-01-15,2023,2023-01-15 22:15:59.024000+00:00,1.347796,2023-01-15 21:24:00+00:00,-0.28,0.866396,0h 52m after,71,51.824818,100.0,137
71,Takapuwahia_Nov25,2025-12-08,2025,2025-12-08 22:25:51.025000+00:00,4.890863,2025-12-08 18:20:00+00:00,-0.46,4.097507,4h 06m after,69,50.364964,100.0,137
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,Takapuwahia_Nov25,2023-08-28,2023,2023-08-28 22:16:11.024000+00:00,4.629065,2023-08-29 02:59:00+00:00,-0.41,-4.713604,4h 43m before,0,0.000000,100.0,137
51,Takapuwahia_Nov25,2025-01-17,2025,2025-01-17 22:25:39.024000+00:00,8.726227,2025-01-17 18:17:00+00:00,-0.51,4.144173,4h 09m after,0,0.000000,100.0,137
46,Takapuwahia_Nov25,2024-09-24,2024,2024-09-24 22:25:41.024000+00:00,5.542720,2024-09-24 19:40:00+00:00,-0.27,2.761396,2h 46m after,0,0.000000,100.0,137
43,Takapuwahia_Nov25,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,3.418219,2024-08-20 16:47:00+00:00,-0.67,5.644173,5h 39m after,0,0.000000,100.0,137
59,Takapuwahia_Nov25,2025-05-02,2025,2025-05-02 22:26:01.025000+00:00,5.353211,2025-05-02 18:50:00+00:00,-0.40,3.600285,3h 36m after,0,0.000000,100.0,137

ThePoint_Feb26: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Feb26\ThePoint_Feb26_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Feb26\ThePoint_Feb26_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Feb26\ThePoint_Feb26_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Feb26\ThePoint_Feb26_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
17,ThePoint_Feb26,2023-05-30,2023,2023-05-30 22:16:11.024000+00:00,5.582327,2023-05-31 01:00:00+00:00,-0.32,-2.730271,2h 44m before,298,33.710407,100.0,884
72,ThePoint_Feb26,2025-12-23,2025,2025-12-23 22:25:39.024000+00:00,7.287385,2025-12-23 18:02:00+00:00,-0.47,4.394173,4h 24m after,186,21.040724,100.0,884
25,ThePoint_Feb26,2023-09-07,2023,2023-09-07 22:16:11.024000+00:00,0.000348,2023-09-07 20:24:00+00:00,-0.22,1.869729,1h 52m after,162,18.325792,100.0,884
20,ThePoint_Feb26,2023-06-12,2023,2023-06-12 22:25:51.024000+00:00,0.632771,2023-06-12 23:38:00+00:00,-0.28,-1.202493,1h 12m before,160,18.099548,100.0,884
19,ThePoint_Feb26,2023-06-07,2023,2023-06-07 22:25:49.024000+00:00,0.799076,2023-06-07 18:20:00+00:00,-0.51,4.096951,4h 06m after,154,17.420814,100.0,884
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,ThePoint_Feb26,2022-04-25,2022,2022-04-25 22:16:11.024000+00:00,4.320996,2022-04-26 00:55:00+00:00,-0.22,-2.646938,2h 39m before,0,0.000000,100.0,884
32,ThePoint_Feb26,2024-03-28,2024,2024-03-28 22:25:41.024000+00:00,4.112476,2024-03-28 17:39:00+00:00,-0.59,4.778062,4h 47m after,0,0.000000,100.0,884
10,ThePoint_Feb26,2023-01-13,2023,2023-01-13 22:25:41.024000+00:00,6.727295,2023-01-13 19:45:00+00:00,-0.39,2.678062,2h 41m after,0,0.000000,100.0,884
51,ThePoint_Feb26,2025-01-17,2025,2025-01-17 22:25:39.024000+00:00,8.726227,2025-01-17 18:16:00+00:00,-0.52,4.160840,4h 10m after,0,0.000000,100.0,884
43,ThePoint_Feb26,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,3.418219,2024-08-20 16:45:00+00:00,-0.68,5.677507,5h 41m after,0,0.000000,100.0,884

ThePoint_Nov25: search 2022-2025
  Distinct cloud-filtered dates: 73
  Saved 73 scene rows: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Nov25\ThePoint_Nov25_2022-2025_dry_area_lowtide-duration-v4.csv
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Nov25\ThePoint_Nov25_2022-2025_rgb_lowtide-duration-v4.html
  Saved gallery: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Nov25\ThePoint_Nov25_2022-2025_scl_lowtide-duration-v4.html
  Saved scatter: C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Nov25\ThePoint_Nov25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

,site,date,year,satellite_time_utc,cloud_cover_pct,nearest_low_tide_time_utc,nearest_low_tide_height_msl,hours_from_low_tide,duration_from_low_tide,dry_pixels_scl_4_5,dry_area_pct,scl_coverage_pct,site_pixels
17,ThePoint_Nov25,2023-05-30,2023,2023-05-30 22:16:11.024000+00:00,5.582327,2023-05-31 01:00:00+00:00,-0.32,-2.730271,2h 44m before,299,33.785311,100.0,885
72,ThePoint_Nov25,2025-12-23,2025,2025-12-23 22:25:39.024000+00:00,7.287385,2025-12-23 18:02:00+00:00,-0.47,4.394173,4h 24m after,186,21.016949,100.0,885
25,ThePoint_Nov25,2023-09-07,2023,2023-09-07 22:16:11.024000+00:00,0.000348,2023-09-07 20:24:00+00:00,-0.22,1.869729,1h 52m after,163,18.418079,100.0,885
20,ThePoint_Nov25,2023-06-12,2023,2023-06-12 22:25:51.024000+00:00,0.632771,2023-06-12 23:38:00+00:00,-0.28,-1.202493,1h 12m before,161,18.192090,100.0,885
19,ThePoint_Nov25,2023-06-07,2023,2023-06-07 22:25:49.024000+00:00,0.799076,2023-06-07 18:20:00+00:00,-0.51,4.096951,4h 06m after,155,17.514124,100.0,885
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,ThePoint_Nov25,2022-04-25,2022,2022-04-25 22:16:11.024000+00:00,4.320996,2022-04-26 00:55:00+00:00,-0.22,-2.646938,2h 39m before,0,0.000000,100.0,885
32,ThePoint_Nov25,2024-03-28,2024,2024-03-28 22:25:41.024000+00:00,4.112476,2024-03-28 17:39:00+00:00,-0.59,4.778062,4h 47m after,0,0.000000,100.0,885
10,ThePoint_Nov25,2023-01-13,2023,2023-01-13 22:25:41.024000+00:00,6.727295,2023-01-13 19:45:00+00:00,-0.39,2.678062,2h 41m after,0,0.000000,100.0,885
51,ThePoint_Nov25,2025-01-17,2025,2025-01-17 22:25:39.024000+00:00,8.726227,2025-01-17 18:16:00+00:00,-0.52,4.160840,4h 10m after,0,0.000000,100.0,885
43,ThePoint_Nov25,2024-08-20,2024,2024-08-20 22:25:39.024000+00:00,3.418219,2024-08-20 16:45:00+00:00,-0.68,5.677507,5h 41m after,0,0.000000,100.0,885

Completed 20 of 20 sites.
Per-site outputs:

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsLake\CatlinsLake_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsLake\CatlinsLake_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsLake\CatlinsLake_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsLake\CatlinsLake_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsRiverMouth\CatlinsRiverMouth_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsRiverMouth\CatlinsRiverMouth_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsRiverMouth\CatlinsRiverMouth_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\CatlinsRiverMouth\CatlinsRiverMouth_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Childrens\Childrens_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Childrens\Childrens_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Childrens\Childrens_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Childrens\Childrens_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Duvauchelle\Duvauchelle_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Duvauchelle\Duvauchelle_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Duvauchelle\Duvauchelle_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Duvauchelle\Duvauchelle_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Ihutai\Ihutai_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Ihutai\Ihutai_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Ihutai\Ihutai_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Ihutai\Ihutai_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Feb26\IveyBay_Feb26_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Feb26\IveyBay_Feb26_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Feb26\IveyBay_Feb26_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Feb26\IveyBay_Feb26_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Nov25\IveyBay_Nov25_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Nov25\IveyBay_Nov25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Nov25\IveyBay_Nov25_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_Nov25\IveyBay_Nov25_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\IveyBay_ThePoint_LeftBank_Oct24\IveyBay_ThePoint_LeftBank_Oct24_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Feb26\LeftBank_Feb26_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Feb26\LeftBank_Feb26_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Feb26\LeftBank_Feb26_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Feb26\LeftBank_Feb26_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Nov25\LeftBank_Nov25_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Nov25\LeftBank_Nov25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Nov25\LeftBank_Nov25_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\LeftBank_Nov25\LeftBank_Nov25_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb25\Paremata_Feb25_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb25\Paremata_Feb25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb25\Paremata_Feb25_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb25\Paremata_Feb25_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb26\Paremata_Feb26_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb26\Paremata_Feb26_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb26\Paremata_Feb26_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Feb26\Paremata_Feb26_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Nov25\Paremata_Nov25_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Nov25\Paremata_Nov25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Nov25\Paremata_Nov25_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Paremata_Nov25\Paremata_Nov25_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Purau\Purau_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Purau\Purau_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Purau\Purau_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Purau\Purau_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Robinsons\Robinsons_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Robinsons\Robinsons_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Robinsons\Robinsons_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Robinsons\Robinsons_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takamatua\Takamatua_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takamatua\Takamatua_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takamatua\Takamatua_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takamatua\Takamatua_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Feb26\Takapuwahia_Feb26_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Feb26\Takapuwahia_Feb26_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Feb26\Takapuwahia_Feb26_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Feb26\Takapuwahia_Feb26_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Nov25\Takapuwahia_Nov25_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Nov25\Takapuwahia_Nov25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Nov25\Takapuwahia_Nov25_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\Takapuwahia_Nov25\Takapuwahia_Nov25_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Feb26\ThePoint_Feb26_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Feb26\ThePoint_Feb26_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Feb26\ThePoint_Feb26_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Feb26\ThePoint_Feb26_2022-2025_scl_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Nov25\ThePoint_Nov25_2022-2025_dry_area_lowtide-duration-v4.csv

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Nov25\ThePoint_Nov25_2022-2025_dry_vs_low_tide_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Nov25\ThePoint_Nov25_2022-2025_rgb_lowtide-duration-v4.html

C:\Local\repos\seagrass-detection\data\analysis\all_sites_tide_exposure\ThePoint_Nov25\ThePoint_Nov25_2022-2025_scl_lowtide-duration-v4.html